"""
    ____                      __      ____
   /\  _`\   __             /'_ `\   /\  _`\
   \ \ \L\_\/\_\    __  _  /\ \L\ \  \ \ \L\ \ _ __    ___
    \ \  _\/\/\ \  /\ \/'\ \/_> _ <_  \ \ ,__//\`'__\ / __`\
     \ \ \/  \ \ \ \/>  </   /\ \L\ \  \ \ \/ \ \ \/ /\ \L\ \
      \ \_\   \ \_\ /\_/\_\  \ \____/   \ \_\  \ \_\ \ \____/
       \/_/    \/_/ \//\/_/   \/___/     \/_/   \/_/  \/___/

               Fix8Pro FIX Engine and Framework

Copyright (C) 2010-19 Fix8 Market Technologies Pty Ltd (ABN 29 167 027 198)
All Rights Reserved. [http://www.fix8mt.com] <heretohelp@fix8mt.com>

THIS FILE IS PROPRIETARY AND  CONFIDENTIAL. NO PART OF THIS FILE MAY BE REPRODUCED,  STORED
IN A RETRIEVAL SYSTEM,  OR TRANSMITTED, IN ANY FORM OR ANY MEANS,  ELECTRONIC, PHOTOSTATIC,
RECORDED OR OTHERWISE, WITHOUT THE PRIOR AND  EXPRESS WRITTEN  PERMISSION  OF  FIX8  MARKET
TECHNOLOGIES PTY LTD.
"""

# Autogenerated on 2019-09-03 12:58:11.936718
# /home/sergey/src/f8/fix8pro/compiler/py/f8c/f8c.py --template ufe_java_fields ufe_cpp_fields ufe_cs_fields ufe_py_fields --output-dir ./generated --schema-dir /home/sergey/src/f8/fix8pro/schema/xml FIX50SP2 FIX42 FIX44 FIX40 FIX41 FIX43 FIX50 FIX50SP1
# DO NOT EDIT!
# 4 spaces instead of tab is required

class FIX41_Fields:

    # Account(1): CHAR
    class Account:
        tag: int = 1

    # AdvId(2): CHAR
    class AdvId:
        tag: int = 2

    # AdvRefID(3): CHAR
    class AdvRefID:
        tag: int = 3

    # AdvSide(4): CHAR
    class AdvSide:
        tag: int = 4
        BUY: str = 'B'
        SELL: str = 'S'
        TRADE: str = 'T'
        CROSS: str = 'X'

    # AdvTransType(5): CHAR
    class AdvTransType:
        tag: int = 5
        CANCEL: str = 'C'
        NEW: str = 'N'
        REPLACE: str = 'R'

    # AvgPx(6): FLOAT
    class AvgPx:
        tag: int = 6

    # BeginSeqNo(7): INT
    class BeginSeqNo:
        tag: int = 7

    # BeginString(8): CHAR
    class BeginString:
        tag: int = 8

    # BodyLength(9): INT
    class BodyLength:
        tag: int = 9

    # CheckSum(10): CHAR
    class CheckSum:
        tag: int = 10

    # ClOrdID(11): CHAR
    class ClOrdID:
        tag: int = 11

    # Commission(12): FLOAT
    class Commission:
        tag: int = 12

    # CommType(13): CHAR
    class CommType:
        tag: int = 13
        PER_SHARE: str = '1'
        PERCENTAGE: str = '2'
        ABSOLUTE: str = '3'

    # CumQty(14): INT
    class CumQty:
        tag: int = 14

    # Currency(15): CHAR
    class Currency:
        tag: int = 15

    # EndSeqNo(16): INT
    class EndSeqNo:
        tag: int = 16

    # ExecID(17): CHAR
    class ExecID:
        tag: int = 17

    # ExecInst(18): CHAR
    class ExecInst:
        tag: int = 18
        STAY_ON_OFFERSIDE: str = '0'
        NOT_HELD: str = '1'
        WORK: str = '2'
        GO_ALONG: str = '3'
        OVER_THE_DAY: str = '4'
        HELD: str = '5'
        PARTICIPATE_DONT_INITIATE: str = '6'
        STRICT_SCALE: str = '7'
        TRY_TO_SCALE: str = '8'
        STAY_ON_BIDSIDE: str = '9'
        NO_CROSS: str = 'A'
        OK_TO_CROSS: str = 'B'
        CALL_FIRST: str = 'C'
        PERCENT_OF_VOLUME: str = 'D'
        DO_NOT_INCREASE: str = 'E'
        DO_NOT_REDUCE: str = 'F'
        ALL_OR_NONE: str = 'G'
        INSTITUTIONS_ONLY: str = 'I'
        LAST_PEG: str = 'L'
        MID_PRICE_PEG: str = 'M'
        NON_NEGOTIABLE: str = 'N'
        OPENING_PEG: str = 'O'
        MARKET_PEG: str = 'P'
        PRIMARY_PEG: str = 'R'
        SUSPEND: str = 'S'
        CUSTOMER_DISPLAY_INSTRUCTION: str = 'U'
        NETTING: str = 'V'

    # ExecRefID(19): CHAR
    class ExecRefID:
        tag: int = 19

    # ExecTransType(20): CHAR
    class ExecTransType:
        tag: int = 20
        NEW: str = '0'
        CANCEL: str = '1'
        CORRECT: str = '2'
        STATUS: str = '3'

    # HandlInst(21): CHAR
    class HandlInst:
        tag: int = 21
        AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION: str = '1'
        AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK: str = '2'
        MANUAL_ORDER_BEST_EXECUTION: str = '3'

    # IDSource(22): CHAR
    class IDSource:
        tag: int = 22
        CUSIP: str = '1'
        SEDOL: str = '2'
        QUIK: str = '3'
        ISIN_NUMBER: str = '4'
        RIC_CODE: str = '5'
        ISO_CURRENCY_CODE: str = '6'
        ISO_COUNTRY_CODE: str = '7'

    # IOIid(23): CHAR
    class IOIid:
        tag: int = 23

    # IOIOthSvc(24): CHAR
    class IOIOthSvc:
        tag: int = 24
        AUTEX: str = 'A'
        BRIDGE: str = 'B'

    # IOIQltyInd(25): CHAR
    class IOIQltyInd:
        tag: int = 25
        HIGH: str = 'H'
        LOW: str = 'L'
        MEDIUM: str = 'M'

    # IOIRefID(26): CHAR
    class IOIRefID:
        tag: int = 26

    # IOIShares(27): CHAR
    class IOIShares:
        tag: int = 27
        LARGE: str = 'L'
        MEDIUM: str = 'M'
        SMALL: str = 'S'

    # IOITransType(28): CHAR
    class IOITransType:
        tag: int = 28
        CANCEL: str = 'C'
        NEW: str = 'N'
        REPLACE: str = 'R'

    # LastCapacity(29): CHAR
    class LastCapacity:
        tag: int = 29
        AGENT: str = '1'
        CROSS_AS_AGENT: str = '2'
        CROSS_AS_PRINCIPAL: str = '3'
        PRINCIPAL: str = '4'

    # LastMkt(30): CHAR
    class LastMkt:
        tag: int = 30

    # LastPx(31): FLOAT
    class LastPx:
        tag: int = 31

    # LastShares(32): INT
    class LastShares:
        tag: int = 32

    # LinesOfText(33): INT
    class LinesOfText:
        tag: int = 33

    # MsgSeqNum(34): INT
    class MsgSeqNum:
        tag: int = 34

    # MsgType(35): STRING
    class MsgType:
        tag: int = 35
        HEARTBEAT: str = "0"
        TEST_REQUEST: str = "1"
        RESEND_REQUEST: str = "2"
        REJECT: str = "3"
        SEQUENCE_RESET: str = "4"
        LOGOUT: str = "5"
        INDICATION_OF_INTEREST: str = "6"
        ADVERTISEMENT: str = "7"
        EXECUTION_REPORT: str = "8"
        ORDER_CANCEL_REJECT: str = "9"
        LOGON: str = "A"
        NEWS: str = "B"
        EMAIL: str = "C"
        ORDER_D: str = "D"
        ORDER_E: str = "E"
        ORDER_CANCEL_REQUEST: str = "F"
        ORDER_CANCEL_REPLACE_REQUEST: str = "G"
        ORDER_STATUS_REQUEST: str = "H"
        ALLOCATION: str = "J"
        LIST_CANCEL_REQUEST: str = "K"
        LIST_EXECUTE: str = "L"
        LIST_STATUS_REQUEST: str = "M"
        LIST_STATUS: str = "N"
        ALLOCATION_ACK: str = "P"
        DONT_KNOW_TRADE: str = "Q"
        QUOTE_REQUEST: str = "R"
        QUOTE: str = "S"
        SETTLEMENT_INSTRUCTIONS: str = "T"

    # NewSeqNo(36): INT
    class NewSeqNo:
        tag: int = 36

    # OrderID(37): CHAR
    class OrderID:
        tag: int = 37

    # OrderQty(38): INT
    class OrderQty:
        tag: int = 38

    # OrdStatus(39): CHAR
    class OrdStatus:
        tag: int = 39
        NEW: str = '0'
        PARTIALLY_FILLED: str = '1'
        FILLED: str = '2'
        DONE_FOR_DAY: str = '3'
        CANCELED: str = '4'
        REPLACED: str = '5'
        PENDING_CANCEL_REPLACE: str = '6'
        STOPPED: str = '7'
        REJECTED: str = '8'
        SUSPENDED: str = '9'
        PENDING_NEW: str = 'A'
        CALCULATED: str = 'B'
        EXPIRED: str = 'C'

    # OrdType(40): CHAR
    class OrdType:
        tag: int = 40
        MARKET: str = '1'
        LIMIT: str = '2'
        STOP: str = '3'
        STOP_LIMIT: str = '4'
        MARKET_ON_CLOSE: str = '5'
        WITH_OR_WITHOUT: str = '6'
        LIMIT_OR_BETTER: str = '7'
        LIMIT_WITH_OR_WITHOUT: str = '8'
        ON_BASIS: str = '9'
        ON_CLOSE: str = 'A'
        LIMIT_ON_CLOSE: str = 'B'
        FOREX_C: str = 'C'
        PREVIOUSLY_QUOTED: str = 'D'
        PREVIOUSLY_INDICATED: str = 'E'
        FOREX_F: str = 'F'
        FOREX_G: str = 'G'
        FOREX_H: str = 'H'
        PEGGED: str = 'P'

    # OrigClOrdID(41): CHAR
    class OrigClOrdID:
        tag: int = 41

    # OrigTime(42): UTCTIMESTAMP
    class OrigTime:
        tag: int = 42

    # PossDupFlag(43): CHAR
    class PossDupFlag:
        tag: int = 43
        NO: str = 'N'
        YES: str = 'Y'

    # Price(44): FLOAT
    class Price:
        tag: int = 44

    # RefSeqNum(45): INT
    class RefSeqNum:
        tag: int = 45

    # RelatdSym(46): CHAR
    class RelatdSym:
        tag: int = 46

    # Rule80A(47): CHAR
    class Rule80A:
        tag: int = 47
        AGENCY_SINGLE_ORDER: str = 'A'
        SHORT_EXEMPT_TRANSACTION_B: str = 'B'
        PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG: str = 'C'
        PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG: str = 'D'
        REGISTERED_EQUITY_MARKET_MAKER_TRADES: str = 'E'
        SHORT_EXEMPT_TRANSACTION_F: str = 'F'
        SHORT_EXEMPT_TRANSACTION_H: str = 'H'
        INDIVIDUAL_INVESTOR_SINGLE_ORDER: str = 'I'
        PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER: str = 'J'
        PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER: str = 'K'
        SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE: str = 'L'
        PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER: str = 'M'
        PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER: str = 'N'
        COMPETING_DEALER_TRADES_O: str = 'O'
        PRINCIPAL: str = 'P'
        COMPETING_DEALER_TRADES_R: str = 'R'
        SPECIALIST_TRADES: str = 'S'
        COMPETING_DEALER_TRADES_T: str = 'T'
        PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY: str = 'U'
        ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER: str = 'W'
        SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE: str = 'X'
        PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY: str = 'Y'
        SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER: str = 'Z'

    # SecurityID(48): CHAR
    class SecurityID:
        tag: int = 48

    # SenderCompID(49): CHAR
    class SenderCompID:
        tag: int = 49

    # SenderSubID(50): CHAR
    class SenderSubID:
        tag: int = 50

    # SendingDate(51): LOCALMKTDATE
    class SendingDate:
        tag: int = 51

    # SendingTime(52): UTCTIMESTAMP
    class SendingTime:
        tag: int = 52

    # Shares(53): INT
    class Shares:
        tag: int = 53

    # Side(54): CHAR
    class Side:
        tag: int = 54
        BUY: str = '1'
        SELL: str = '2'
        BUY_MINUS: str = '3'
        SELL_PLUS: str = '4'
        SELL_SHORT: str = '5'
        SELL_SHORT_EXEMPT: str = '6'
        UNDISCLOSED: str = '7'
        CROSS: str = '8'

    # Symbol(55): CHAR
    class Symbol:
        tag: int = 55

    # TargetCompID(56): CHAR
    class TargetCompID:
        tag: int = 56

    # TargetSubID(57): CHAR
    class TargetSubID:
        tag: int = 57

    # Text(58): CHAR
    class Text:
        tag: int = 58

    # TimeInForce(59): CHAR
    class TimeInForce:
        tag: int = 59
        DAY: str = '0'
        GOOD_TILL_CANCEL: str = '1'
        AT_THE_OPENING: str = '2'
        IMMEDIATE_OR_CANCEL: str = '3'
        FILL_OR_KILL: str = '4'
        GOOD_TILL_CROSSING: str = '5'
        GOOD_TILL_DATE: str = '6'

    # TransactTime(60): UTCTIMESTAMP
    class TransactTime:
        tag: int = 60

    # Urgency(61): CHAR
    class Urgency:
        tag: int = 61
        NORMAL: str = '0'
        FLASH: str = '1'
        BACKGROUND: str = '2'

    # ValidUntilTime(62): UTCTIMESTAMP
    class ValidUntilTime:
        tag: int = 62

    # SettlmntTyp(63): CHAR
    class SettlmntTyp:
        tag: int = 63
        REGULAR: str = '0'
        CASH: str = '1'
        NEXT_DAY: str = '2'
        T_PLUS_2: str = '3'
        T_PLUS_3: str = '4'
        T_PLUS_4: str = '5'
        FUTURE: str = '6'
        WHEN_ISSUED: str = '7'
        SELLERS_OPTION: str = '8'
        T_PLUS_5: str = '9'

    # FutSettDate(64): LOCALMKTDATE
    class FutSettDate:
        tag: int = 64

    # SymbolSfx(65): CHAR
    class SymbolSfx:
        tag: int = 65

    # ListID(66): CHAR
    class ListID:
        tag: int = 66

    # ListSeqNo(67): INT
    class ListSeqNo:
        tag: int = 67

    # ListNoOrds(68): INT
    class ListNoOrds:
        tag: int = 68

    # ListExecInst(69): CHAR
    class ListExecInst:
        tag: int = 69

    # AllocID(70): CHAR
    class AllocID:
        tag: int = 70

    # AllocTransType(71): CHAR
    class AllocTransType:
        tag: int = 71
        NEW: str = '0'
        REPLACE: str = '1'
        CANCEL: str = '2'
        PRELIMINARY: str = '3'
        CALCULATED: str = '4'

    # RefAllocID(72): CHAR
    class RefAllocID:
        tag: int = 72

    # NoOrders(73): INT
    class NoOrders:
        tag: int = 73

    # AvgPrxPrecision(74): INT
    class AvgPrxPrecision:
        tag: int = 74

    # TradeDate(75): LOCALMKTDATE
    class TradeDate:
        tag: int = 75

    # ExecBroker(76): CHAR
    class ExecBroker:
        tag: int = 76

    # OpenClose(77): CHAR
    class OpenClose:
        tag: int = 77
        CLOSE: str = 'C'
        OPEN: str = 'O'

    # NoAllocs(78): INT
    class NoAllocs:
        tag: int = 78

    # AllocAccount(79): CHAR
    class AllocAccount:
        tag: int = 79

    # AllocShares(80): INT
    class AllocShares:
        tag: int = 80

    # ProcessCode(81): CHAR
    class ProcessCode:
        tag: int = 81
        REGULAR: str = '0'
        SOFT_DOLLAR: str = '1'
        STEP_IN: str = '2'
        STEP_OUT: str = '3'
        SOFT_DOLLAR_STEP_IN: str = '4'
        SOFT_DOLLAR_STEP_OUT: str = '5'
        PLAN_SPONSOR: str = '6'

    # NoRpts(82): INT
    class NoRpts:
        tag: int = 82

    # RptSeq(83): INT
    class RptSeq:
        tag: int = 83

    # CxlQty(84): INT
    class CxlQty:
        tag: int = 84

    # NoDlvyInst(85): INT
    class NoDlvyInst:
        tag: int = 85

    # DlvyInst(86): CHAR
    class DlvyInst:
        tag: int = 86

    # AllocStatus(87): INT
    class AllocStatus:
        tag: int = 87
        ACCEPTED: int = 0
        REJECTED: int = 1
        PARTIAL_ACCEPT: int = 2
        RECEIVED: int = 3

    # AllocRejCode(88): INT
    class AllocRejCode:
        tag: int = 88
        UNKNOWN_ACCOUNT: int = 0
        INCORRECT_QUANTITY: int = 1
        INCORRECT_AVERAGE_PRICE: int = 2
        UNKNOWN_EXECUTING_BROKER_MNEMONIC: int = 3
        COMMISSION_DIFFERENCE: int = 4
        UNKNOWN_ORDERID: int = 5
        UNKNOWN_LISTID: int = 6
        OTHER: int = 7

    # Signature(89): DATA
    class Signature:
        tag: int = 89

    # SecureDataLen(90): LENGTH
    class SecureDataLen:
        tag: int = 90

    # SecureData(91): DATA
    class SecureData:
        tag: int = 91

    # BrokerOfCredit(92): CHAR
    class BrokerOfCredit:
        tag: int = 92

    # SignatureLength(93): LENGTH
    class SignatureLength:
        tag: int = 93

    # EmailType(94): CHAR
    class EmailType:
        tag: int = 94
        NEW: str = '0'
        REPLY: str = '1'
        ADMIN_REPLY: str = '2'

    # RawDataLength(95): LENGTH
    class RawDataLength:
        tag: int = 95

    # RawData(96): DATA
    class RawData:
        tag: int = 96

    # PossResend(97): CHAR
    class PossResend:
        tag: int = 97
        NO: str = 'N'
        YES: str = 'Y'

    # EncryptMethod(98): INT
    class EncryptMethod:
        tag: int = 98
        NONE: int = 0
        PKCS: int = 1
        DES: int = 2
        PKCS_DES: int = 3
        PGP_DES: int = 4
        PGP_DES_MD5: int = 5
        PEM_DES_MD5: int = 6

    # StopPx(99): FLOAT
    class StopPx:
        tag: int = 99

    # ExDestination(100): CHAR
    class ExDestination:
        tag: int = 100

    # CxlRejReason(102): INT
    class CxlRejReason:
        tag: int = 102
        TOO_LATE_TO_CANCEL: int = 0
        UNKNOWN_ORDER: int = 1

    # OrdRejReason(103): INT
    class OrdRejReason:
        tag: int = 103
        BROKER_OPTION: int = 0
        UNKNOWN_SYMBOL: int = 1
        EXCHANGE_CLOSED: int = 2
        ORDER_EXCEEDS_LIMIT: int = 3
        TOO_LATE_TO_ENTER: int = 4
        UNKNOWN_ORDER: int = 5
        DUPLICATE_ORDER: int = 6

    # IOIQualifier(104): CHAR
    class IOIQualifier:
        tag: int = 104
        ALL_OR_NONE: str = 'A'
        AT_THE_CLOSE: str = 'C'
        IN_TOUCH_WITH: str = 'I'
        LIMIT: str = 'L'
        MORE_BEHIND: str = 'M'
        AT_THE_OPEN: str = 'O'
        TAKING_A_POSITION: str = 'P'
        AT_THE_MARKET: str = 'Q'
        PORTFOLIO_SHOW_N: str = 'S'
        THROUGH_THE_DAY: str = 'T'
        VERSUS: str = 'V'
        INDICATION: str = 'W'
        CROSSING_OPPORTUNITY: str = 'X'
        AT_THE_MIDPOINT: str = 'Y'
        PRE_OPEN: str = 'Z'

    # WaveNo(105): CHAR
    class WaveNo:
        tag: int = 105

    # Issuer(106): CHAR
    class Issuer:
        tag: int = 106

    # SecurityDesc(107): CHAR
    class SecurityDesc:
        tag: int = 107

    # HeartBtInt(108): INT
    class HeartBtInt:
        tag: int = 108

    # ClientID(109): CHAR
    class ClientID:
        tag: int = 109

    # MinQty(110): INT
    class MinQty:
        tag: int = 110

    # MaxFloor(111): INT
    class MaxFloor:
        tag: int = 111

    # TestReqID(112): CHAR
    class TestReqID:
        tag: int = 112

    # ReportToExch(113): CHAR
    class ReportToExch:
        tag: int = 113
        NO: str = 'N'
        YES: str = 'Y'

    # LocateReqd(114): CHAR
    class LocateReqd:
        tag: int = 114
        NO: str = 'N'
        YES: str = 'Y'

    # OnBehalfOfCompID(115): CHAR
    class OnBehalfOfCompID:
        tag: int = 115

    # OnBehalfOfSubID(116): CHAR
    class OnBehalfOfSubID:
        tag: int = 116

    # QuoteID(117): CHAR
    class QuoteID:
        tag: int = 117

    # NetMoney(118): FLOAT
    class NetMoney:
        tag: int = 118

    # SettlCurrAmt(119): FLOAT
    class SettlCurrAmt:
        tag: int = 119

    # SettlCurrency(120): CHAR
    class SettlCurrency:
        tag: int = 120

    # ForexReq(121): CHAR
    class ForexReq:
        tag: int = 121
        NO: str = 'N'
        YES: str = 'Y'

    # OrigSendingTime(122): UTCTIMESTAMP
    class OrigSendingTime:
        tag: int = 122

    # GapFillFlag(123): CHAR
    class GapFillFlag:
        tag: int = 123
        NO: str = 'N'
        YES: str = 'Y'

    # NoExecs(124): INT
    class NoExecs:
        tag: int = 124

    # CxlType(125):  CHAR
    class CxlType:
        tag: int = 125

    # ExpireTime(126): UTCTIMESTAMP
    class ExpireTime:
        tag: int = 126

    # DKReason(127): CHAR
    class DKReason:
        tag: int = 127
        UNKNOWN_SYMBOL: str = 'A'
        WRONG_SIDE: str = 'B'
        QUANTITY_EXCEEDS_ORDER: str = 'C'
        NO_MATCHING_ORDER: str = 'D'
        PRICE_EXCEEDS_LIMIT: str = 'E'
        OTHER: str = 'Z'

    # DeliverToCompID(128): CHAR
    class DeliverToCompID:
        tag: int = 128

    # DeliverToSubID(129): CHAR
    class DeliverToSubID:
        tag: int = 129

    # IOINaturalFlag(130): CHAR
    class IOINaturalFlag:
        tag: int = 130
        NO: str = 'N'
        YES: str = 'Y'

    # QuoteReqID(131): CHAR
    class QuoteReqID:
        tag: int = 131

    # BidPx(132): FLOAT
    class BidPx:
        tag: int = 132

    # OfferPx(133): FLOAT
    class OfferPx:
        tag: int = 133

    # BidSize(134): INT
    class BidSize:
        tag: int = 134

    # OfferSize(135): INT
    class OfferSize:
        tag: int = 135

    # NoMiscFees(136): INT
    class NoMiscFees:
        tag: int = 136

    # MiscFeeAmt(137): FLOAT
    class MiscFeeAmt:
        tag: int = 137

    # MiscFeeCurr(138): CHAR
    class MiscFeeCurr:
        tag: int = 138

    # MiscFeeType(139): CHAR
    class MiscFeeType:
        tag: int = 139
        REGULATORY: str = '1'
        TAX: str = '2'
        LOCAL_COMMISSION: str = '3'
        EXCHANGE_FEES: str = '4'
        STAMP: str = '5'
        LEVY: str = '6'
        OTHER: str = '7'
        MARKUP: str = '8'

    # PrevClosePx(140): FLOAT
    class PrevClosePx:
        tag: int = 140

    # ResetSeqNumFlag(141): CHAR
    class ResetSeqNumFlag:
        tag: int = 141
        NO: str = 'N'
        YES: str = 'Y'

    # SenderLocationID(142): CHAR
    class SenderLocationID:
        tag: int = 142

    # TargetLocationID(143): CHAR
    class TargetLocationID:
        tag: int = 143

    # OnBehalfOfLocationID(144): CHAR
    class OnBehalfOfLocationID:
        tag: int = 144

    # DeliverToLocationID(145): CHAR
    class DeliverToLocationID:
        tag: int = 145

    # NoRelatedSym(146): INT
    class NoRelatedSym:
        tag: int = 146

    # Subject(147): CHAR
    class Subject:
        tag: int = 147

    # Headline(148): CHAR
    class Headline:
        tag: int = 148

    # URLLink(149): CHAR
    class URLLink:
        tag: int = 149

    # ExecType(150): CHAR
    class ExecType:
        tag: int = 150
        NEW: str = '0'
        PARTIAL_FILL: str = '1'
        FILL: str = '2'
        DONE_FOR_DAY: str = '3'
        CANCELLED: str = '4'
        REPLACE: str = '5'
        PENDING_CANCEL_REPLACE: str = '6'
        STOPPED: str = '7'
        REJECTED: str = '8'
        SUSPENDED: str = '9'
        PENDING_NEW: str = 'A'
        CALCULATED: str = 'B'
        EXPIRED: str = 'C'

    # LeavesQty(151): INT
    class LeavesQty:
        tag: int = 151

    # CashOrderQty(152): FLOAT
    class CashOrderQty:
        tag: int = 152

    # AllocAvgPx(153): FLOAT
    class AllocAvgPx:
        tag: int = 153

    # AllocNetMoney(154): FLOAT
    class AllocNetMoney:
        tag: int = 154

    # SettlCurrFxRate(155): FLOAT
    class SettlCurrFxRate:
        tag: int = 155

    # SettlCurrFxRateCalc(156): CHAR
    class SettlCurrFxRateCalc:
        tag: int = 156
        MULTIPLY: str = 'M'
        DIVIDE: str = 'D'

    # NumDaysInterest(157): INT
    class NumDaysInterest:
        tag: int = 157

    # AccruedInterestRate(158): FLOAT
    class AccruedInterestRate:
        tag: int = 158

    # AccruedInterestAmt(159): FLOAT
    class AccruedInterestAmt:
        tag: int = 159

    # SettlInstMode(160): CHAR
    class SettlInstMode:
        tag: int = 160
        DEFAULT: str = '0'
        STANDING_INSTRUCTIONS_PROVIDED: str = '1'
        SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING: str = '2'
        SPECIFIC_ALLOCATION_ACCOUNT_STANDING: str = '3'

    # AllocText(161): CHAR
    class AllocText:
        tag: int = 161

    # SettlInstID(162): CHAR
    class SettlInstID:
        tag: int = 162

    # SettlInstTransType(163): CHAR
    class SettlInstTransType:
        tag: int = 163
        CANCEL: str = 'C'
        NEW: str = 'N'
        REPLACE: str = 'R'

    # EmailThreadID(164): CHAR
    class EmailThreadID:
        tag: int = 164

    # SettlInstSource(165): CHAR
    class SettlInstSource:
        tag: int = 165
        BROKERS_INSTRUCTIONS: str = '1'
        INSTITUTIONS_INSTRUCTIONS: str = '2'

    # SettlLocation(166): STRING
    class SettlLocation:
        tag: int = 166
        CEDEL: str = "CED"
        DEPOSITORY_TRUST_COMPANY: str = "DTC"
        EUROCLEAR: str = "EUR"
        FEDERAL_BOOK_ENTRY: str = "FED"
        LOCAL_MARKET_SETTLE_LOCATION: str = "ISO Country Code"
        PHYSICAL: str = "PNY"
        PARTICIPANT_TRUST_COMPANY: str = "PTC"

    # SecurityType(167): STRING
    class SecurityType:
        tag: int = 167
        BANKERS_ACCEPTANCE: str = "BA"
        CERTIFICATE_OF_DEPOSIT: str = "CD"
        COLLATERALIZE_MORTGAGE_OBLIGATION: str = "CMO"
        CORPORATE_BOND: str = "CORP"
        COMMERCIAL_PAPER: str = "CP"
        CORPORATE_PRIVATE_PLACEMENT: str = "CPP"
        COMMON_STOCK: str = "CS"
        FEDERAL_HOUSING_AUTHORITY: str = "FHA"
        FEDERAL_HOME_LOAN: str = "FHL"
        FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION: str = "FN"
        FOREIGN_EXCHANGE_CONTRACT: str = "FOR"
        FUTURE: str = "FUT"
        GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION: str = "GN"
        TREASURIES_PLUS_AGENCY_DEBENTURE: str = "GOVT"
        MUTUAL_FUND: str = "MF"
        MORTGAGE_INTEREST_ONLY: str = "MIO"
        MORTGAGE_PRINCIPLE_ONLY: str = "MPO"
        MORTGAGE_PRIVATE_PLACEMENT: str = "MPP"
        MISCELLANEOUS_PASS_THRU: str = "MPT"
        MUNICIPAL_BOND: str = "MUNI"
        NO_ISITC_SECURITY_TYPE: str = "NONE"
        OPTION: str = "OPT"
        PREFERRED_STOCK: str = "PS"
        REPURCHASE_AGREEMENT: str = "RP"
        REVERSE_REPURCHASE_AGREEMENT: str = "RVRP"
        STUDENT_LOAN_MARKETING_ASSOCIATION: str = "SL"
        TIME_DEPOSIT: str = "TD"
        US_TREASURY_BILL: str = "USTB"
        WARRANT: str = "WAR"
        CATS_TIGERS_LIONS: str = "ZOO"

    # EffectiveTime(168): UTCTIMESTAMP
    class EffectiveTime:
        tag: int = 168

    # StandInstDbType(169): INT
    class StandInstDbType:
        tag: int = 169
        OTHER: int = 0
        DTC_SID: int = 1
        THOMSON_ALERT: int = 2
        A_GLOBAL_CUSTODIAN: int = 3

    # StandInstDbName(170): CHAR
    class StandInstDbName:
        tag: int = 170

    # StandInstDbID(171): CHAR
    class StandInstDbID:
        tag: int = 171

    # SettlDeliveryType(172): INT
    class SettlDeliveryType:
        tag: int = 172

    # SettlDepositoryCode(173): CHAR
    class SettlDepositoryCode:
        tag: int = 173

    # SettlBrkrCode(174): CHAR
    class SettlBrkrCode:
        tag: int = 174

    # SettlInstCode(175): CHAR
    class SettlInstCode:
        tag: int = 175

    # SecuritySettlAgentName(176): CHAR
    class SecuritySettlAgentName:
        tag: int = 176

    # SecuritySettlAgentCode(177): CHAR
    class SecuritySettlAgentCode:
        tag: int = 177

    # SecuritySettlAgentAcctNum(178): CHAR
    class SecuritySettlAgentAcctNum:
        tag: int = 178

    # SecuritySettlAgentAcctName(179): CHAR
    class SecuritySettlAgentAcctName:
        tag: int = 179

    # SecuritySettlAgentContactName(180): CHAR
    class SecuritySettlAgentContactName:
        tag: int = 180

    # SecuritySettlAgentContactPhone(181): CHAR
    class SecuritySettlAgentContactPhone:
        tag: int = 181

    # CashSettlAgentName(182): CHAR
    class CashSettlAgentName:
        tag: int = 182

    # CashSettlAgentCode(183): CHAR
    class CashSettlAgentCode:
        tag: int = 183

    # CashSettlAgentAcctNum(184): CHAR
    class CashSettlAgentAcctNum:
        tag: int = 184

    # CashSettlAgentAcctName(185): CHAR
    class CashSettlAgentAcctName:
        tag: int = 185

    # CashSettlAgentContactName(186): CHAR
    class CashSettlAgentContactName:
        tag: int = 186

    # CashSettlAgentContactPhone(187): CHAR
    class CashSettlAgentContactPhone:
        tag: int = 187

    # BidSpotRate(188): FLOAT
    class BidSpotRate:
        tag: int = 188

    # BidForwardPoints(189): FLOAT
    class BidForwardPoints:
        tag: int = 189

    # OfferSpotRate(190): FLOAT
    class OfferSpotRate:
        tag: int = 190

    # OfferForwardPoints(191): FLOAT
    class OfferForwardPoints:
        tag: int = 191

    # OrderQty2(192): FLOAT
    class OrderQty2:
        tag: int = 192

    # FutSettDate2(193): LOCALMKTDATE
    class FutSettDate2:
        tag: int = 193

    # LastSpotRate(194): FLOAT
    class LastSpotRate:
        tag: int = 194

    # LastForwardPoints(195): FLOAT
    class LastForwardPoints:
        tag: int = 195

    # AllocLinkID(196): CHAR
    class AllocLinkID:
        tag: int = 196

    # AllocLinkType(197): INT
    class AllocLinkType:
        tag: int = 197
        F_X_NETTING: int = 0
        F_X_SWAP: int = 1

    # SecondaryOrderID(198): CHAR
    class SecondaryOrderID:
        tag: int = 198

    # NoIOIQualifiers(199): INT
    class NoIOIQualifiers:
        tag: int = 199

    # MaturityMonthYear(200): MONTHYEAR
    class MaturityMonthYear:
        tag: int = 200

    # PutOrCall(201): INT
    class PutOrCall:
        tag: int = 201
        PUT: int = 0
        CALL: int = 1

    # StrikePrice(202): FLOAT
    class StrikePrice:
        tag: int = 202

    # CoveredOrUncovered(203): INT
    class CoveredOrUncovered:
        tag: int = 203
        COVERED: int = 0
        UNCOVERED: int = 1

    # CustomerOrFirm(204): INT
    class CustomerOrFirm:
        tag: int = 204
        CUSTOMER: int = 0
        FIRM: int = 1

    # MaturityDay(205): DAYOFMONTH
    class MaturityDay:
        tag: int = 205

    # OptAttribute(206): CHAR
    class OptAttribute:
        tag: int = 206

    # SecurityExchange(207): CHAR
    class SecurityExchange:
        tag: int = 207

    # NotifyBrokerOfCredit(208): CHAR
    class NotifyBrokerOfCredit:
        tag: int = 208
        NO: str = 'N'
        YES: str = 'Y'

    # AllocHandlInst(209): INT
    class AllocHandlInst:
        tag: int = 209
        MATCH: int = 1
        FORWARD: int = 2
        FORWARD_AND_MATCH: int = 3

    # MaxShow(210): INT
    class MaxShow:
        tag: int = 210

    # PegDifference(211): FLOAT
    class PegDifference:
        tag: int = 211
