"""
    ____                      __      ____
   /\  _`\   __             /'_ `\   /\  _`\
   \ \ \L\_\/\_\    __  _  /\ \L\ \  \ \ \L\ \ _ __    ___
    \ \  _\/\/\ \  /\ \/'\ \/_> _ <_  \ \ ,__//\`'__\ / __`\
     \ \ \/  \ \ \ \/>  </   /\ \L\ \  \ \ \/ \ \ \/ /\ \L\ \
      \ \_\   \ \_\ /\_/\_\  \ \____/   \ \_\  \ \_\ \ \____/
       \/_/    \/_/ \//\/_/   \/___/     \/_/   \/_/  \/___/

               Fix8Pro FIX Engine and Framework

Copyright (C) 2010-19 Fix8 Market Technologies Pty Ltd (ABN 29 167 027 198)
All Rights Reserved. [http://www.fix8mt.com] <heretohelp@fix8mt.com>

THIS FILE IS PROPRIETARY AND  CONFIDENTIAL. NO PART OF THIS FILE MAY BE REPRODUCED,  STORED
IN A RETRIEVAL SYSTEM,  OR TRANSMITTED, IN ANY FORM OR ANY MEANS,  ELECTRONIC, PHOTOSTATIC,
RECORDED OR OTHERWISE, WITHOUT THE PRIOR AND  EXPRESS WRITTEN  PERMISSION  OF  FIX8  MARKET
TECHNOLOGIES PTY LTD.
"""

# Autogenerated on 2019-09-03 12:58:11.177161
# /home/sergey/src/f8/fix8pro/compiler/py/f8c/f8c.py --template ufe_java_fields ufe_cpp_fields ufe_cs_fields ufe_py_fields --output-dir ./generated --schema-dir /home/sergey/src/f8/fix8pro/schema/xml FIX50SP2 FIX42 FIX44 FIX40 FIX41 FIX43 FIX50 FIX50SP1
# DO NOT EDIT!
# 4 spaces instead of tab is required

class FIX42_Fields:

    # Account(1): STRING
    class Account:
        tag: int = 1

    # AdvId(2): STRING
    class AdvId:
        tag: int = 2

    # AdvRefID(3): STRING
    class AdvRefID:
        tag: int = 3

    # AdvSide(4): CHAR
    class AdvSide:
        tag: int = 4
        BUY: str = 'B'
        SELL: str = 'S'
        TRADE: str = 'T'
        CROSS: str = 'X'

    # AdvTransType(5): STRING
    class AdvTransType:
        tag: int = 5
        CANCEL: str = "C"
        NEW: str = "N"
        REPLACE: str = "R"

    # AvgPx(6): PRICE
    class AvgPx:
        tag: int = 6

    # BeginSeqNo(7): INT
    class BeginSeqNo:
        tag: int = 7

    # BeginString(8): STRING
    class BeginString:
        tag: int = 8

    # BodyLength(9): INT
    class BodyLength:
        tag: int = 9

    # CheckSum(10): STRING
    class CheckSum:
        tag: int = 10

    # ClOrdID(11): STRING
    class ClOrdID:
        tag: int = 11

    # Commission(12): AMT
    class Commission:
        tag: int = 12

    # CommType(13): CHAR
    class CommType:
        tag: int = 13
        PER_SHARE: str = '1'
        PERCENTAGE: str = '2'
        ABSOLUTE: str = '3'

    # CumQty(14): QTY
    class CumQty:
        tag: int = 14

    # Currency(15): CURRENCY
    class Currency:
        tag: int = 15

    # EndSeqNo(16): INT
    class EndSeqNo:
        tag: int = 16

    # ExecID(17): STRING
    class ExecID:
        tag: int = 17

    # ExecInst(18): MULTIPLEVALUESTRING
    class ExecInst:
        tag: int = 18
        STAY_ON_OFFERSIDE: str = "0"
        NOT_HELD: str = "1"
        WORK: str = "2"
        GO_ALONG: str = "3"
        OVER_THE_DAY: str = "4"
        HELD: str = "5"
        PARTICIPATE_DONT_INITIATE: str = "6"
        STRICT_SCALE: str = "7"
        TRY_TO_SCALE: str = "8"
        STAY_ON_BIDSIDE: str = "9"
        NO_CROSS: str = "A"
        OK_TO_CROSS: str = "B"
        CALL_FIRST: str = "C"
        PERCENT_OF_VOLUME: str = "D"
        DO_NOT_INCREASE: str = "E"
        DO_NOT_REDUCE: str = "F"
        ALL_OR_NONE: str = "G"
        INSTITUTIONS_ONLY: str = "I"
        LAST_PEG: str = "L"
        MID_PRICE_PEG: str = "M"
        NON_NEGOTIABLE: str = "N"
        OPENING_PEG: str = "O"
        MARKET_PEG: str = "P"
        PRIMARY_PEG: str = "R"
        SUSPEND: str = "S"
        FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER: str = "T"
        CUSTOMER_DISPLAY_INSTRUCTION: str = "U"
        NETTING: str = "V"
        PEG_TO_VWAP: str = "W"

    # ExecRefID(19): STRING
    class ExecRefID:
        tag: int = 19

    # ExecTransType(20): CHAR
    class ExecTransType:
        tag: int = 20
        NEW: str = '0'
        CANCEL: str = '1'
        CORRECT: str = '2'
        STATUS: str = '3'

    # HandlInst(21): CHAR
    class HandlInst:
        tag: int = 21
        AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION: str = '1'
        AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK: str = '2'
        MANUAL_ORDER_BEST_EXECUTION: str = '3'

    # IDSource(22): STRING
    class IDSource:
        tag: int = 22
        CUSIP: str = "1"
        SEDOL: str = "2"
        QUIK: str = "3"
        ISIN_NUMBER: str = "4"
        RIC_CODE: str = "5"
        ISO_CURRENCY_CODE: str = "6"
        ISO_COUNTRY_CODE: str = "7"
        EXCHANGE_SYMBOL: str = "8"
        CONSOLIDATED_TAPE_ASSOCIATION: str = "9"

    # IOIid(23): STRING
    class IOIid:
        tag: int = 23

    # IOIOthSvc(24): CHAR
    class IOIOthSvc:
        tag: int = 24

    # IOIQltyInd(25): CHAR
    class IOIQltyInd:
        tag: int = 25
        HIGH: str = 'H'
        LOW: str = 'L'
        MEDIUM: str = 'M'

    # IOIRefID(26): STRING
    class IOIRefID:
        tag: int = 26

    # IOIShares(27): STRING
    class IOIShares:
        tag: int = 27
        LARGE: str = "L"
        MEDIUM: str = "M"
        SMALL: str = "S"

    # IOITransType(28): CHAR
    class IOITransType:
        tag: int = 28
        CANCEL: str = 'C'
        NEW: str = 'N'
        REPLACE: str = 'R'

    # LastCapacity(29): CHAR
    class LastCapacity:
        tag: int = 29
        AGENT: str = '1'
        CROSS_AS_AGENT: str = '2'
        CROSS_AS_PRINCIPAL: str = '3'
        PRINCIPAL: str = '4'

    # LastMkt(30): EXCHANGE
    class LastMkt:
        tag: int = 30

    # LastPx(31): PRICE
    class LastPx:
        tag: int = 31

    # LastShares(32): QTY
    class LastShares:
        tag: int = 32

    # LinesOfText(33): INT
    class LinesOfText:
        tag: int = 33

    # MsgSeqNum(34): INT
    class MsgSeqNum:
        tag: int = 34

    # MsgType(35): STRING
    class MsgType:
        tag: int = 35
        HEARTBEAT: str = "0"
        TEST_REQUEST: str = "1"
        RESEND_REQUEST: str = "2"
        REJECT: str = "3"
        SEQUENCE_RESET: str = "4"
        LOGOUT: str = "5"
        INDICATION_OF_INTEREST: str = "6"
        ADVERTISEMENT: str = "7"
        EXECUTION_REPORT: str = "8"
        ORDER_CANCEL_REJECT: str = "9"
        QUOTE_STATUS_REQUEST: str = "a"
        LOGON: str = "A"
        NEWS: str = "B"
        QUOTE_ACKNOWLEDGEMENT: str = "b"
        EMAIL: str = "C"
        SECURITY_DEFINITION_REQUEST: str = "c"
        ORDER_SINGLE: str = "D"
        SECURITY_DEFINITION: str = "d"
        ORDER_LIST: str = "E"
        SECURITY_STATUS_REQUEST: str = "e"
        SECURITY_STATUS: str = "f"
        ORDER_CANCEL_REQUEST: str = "F"
        ORDER_CANCEL_REPLACE_REQUEST: str = "G"
        TRADING_SESSION_STATUS_REQUEST: str = "g"
        ORDER_STATUS_REQUEST: str = "H"
        TRADING_SESSION_STATUS: str = "h"
        MASS_QUOTE: str = "i"
        BUSINESS_MESSAGE_REJECT: str = "j"
        ALLOCATION: str = "J"
        LIST_CANCEL_REQUEST: str = "K"
        BID_REQUEST: str = "k"
        BID_RESPONSE: str = "l"
        LIST_EXECUTE: str = "L"
        LIST_STRIKE_PRICE: str = "m"
        LIST_STATUS_REQUEST: str = "M"
        LIST_STATUS: str = "N"
        ALLOCATION_ACK: str = "P"
        DONT_KNOW_TRADE: str = "Q"
        QUOTE_REQUEST: str = "R"
        QUOTE: str = "S"
        SETTLEMENT_INSTRUCTIONS: str = "T"
        MARKET_DATA_REQUEST: str = "V"
        MARKET_DATA_SNAPSHOT_FULL_REFRESH: str = "W"
        MARKET_DATA_INCREMENTAL_REFRESH: str = "X"
        MARKET_DATA_REQUEST_REJECT: str = "Y"
        QUOTE_CANCEL: str = "Z"

    # NewSeqNo(36): INT
    class NewSeqNo:
        tag: int = 36

    # OrderID(37): STRING
    class OrderID:
        tag: int = 37

    # OrderQty(38): QTY
    class OrderQty:
        tag: int = 38

    # OrdStatus(39): CHAR
    class OrdStatus:
        tag: int = 39
        NEW: str = '0'
        PARTIALLY_FILLED: str = '1'
        FILLED: str = '2'
        DONE_FOR_DAY: str = '3'
        CANCELED: str = '4'
        REPLACED: str = '5'
        PENDING_CANCEL: str = '6'
        STOPPED: str = '7'
        REJECTED: str = '8'
        SUSPENDED: str = '9'
        PENDING_NEW: str = 'A'
        CALCULATED: str = 'B'
        EXPIRED: str = 'C'
        ACCEPTED_FOR_BIDDING: str = 'D'
        PENDING_REPLACE: str = 'E'

    # OrdType(40): CHAR
    class OrdType:
        tag: int = 40
        MARKET: str = '1'
        LIMIT: str = '2'
        STOP: str = '3'
        STOP_LIMIT: str = '4'
        MARKET_ON_CLOSE: str = '5'
        WITH_OR_WITHOUT: str = '6'
        LIMIT_OR_BETTER: str = '7'
        LIMIT_WITH_OR_WITHOUT: str = '8'
        ON_BASIS: str = '9'
        ON_CLOSE: str = 'A'
        LIMIT_ON_CLOSE: str = 'B'
        FOREX_C: str = 'C'
        PREVIOUSLY_QUOTED: str = 'D'
        PREVIOUSLY_INDICATED: str = 'E'
        FOREX_F: str = 'F'
        FOREX_G: str = 'G'
        FOREX_H: str = 'H'
        FUNARI: str = 'I'
        PEGGED: str = 'P'

    # OrigClOrdID(41): STRING
    class OrigClOrdID:
        tag: int = 41

    # OrigTime(42): UTCTIMESTAMP
    class OrigTime:
        tag: int = 42

    # PossDupFlag(43): BOOLEAN
    class PossDupFlag:
        tag: int = 43
        NO: str = 'N'
        YES: str = 'Y'

    # Price(44): PRICE
    class Price:
        tag: int = 44

    # RefSeqNum(45): INT
    class RefSeqNum:
        tag: int = 45

    # RelatdSym(46): STRING
    class RelatdSym:
        tag: int = 46

    # Rule80A(47): CHAR
    class Rule80A:
        tag: int = 47
        AGENCY_SINGLE_ORDER: str = 'A'
        SHORT_EXEMPT_TRANSACTION_B: str = 'B'
        PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG: str = 'C'
        PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG: str = 'D'
        REGISTERED_EQUITY_MARKET_MAKER_TRADES: str = 'E'
        SHORT_EXEMPT_TRANSACTION_F: str = 'F'
        SHORT_EXEMPT_TRANSACTION_H: str = 'H'
        INDIVIDUAL_INVESTOR_SINGLE_ORDER: str = 'I'
        PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER: str = 'J'
        PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER: str = 'K'
        SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE: str = 'L'
        PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER: str = 'M'
        PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER: str = 'N'
        COMPETING_DEALER_TRADES_O: str = 'O'
        PRINCIPAL: str = 'P'
        COMPETING_DEALER_TRADES_R: str = 'R'
        SPECIALIST_TRADES: str = 'S'
        COMPETING_DEALER_TRADES_T: str = 'T'
        PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY: str = 'U'
        ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER: str = 'W'
        SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE: str = 'X'
        PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY: str = 'Y'
        SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER: str = 'Z'

    # SecurityID(48): STRING
    class SecurityID:
        tag: int = 48

    # SenderCompID(49): STRING
    class SenderCompID:
        tag: int = 49

    # SenderSubID(50): STRING
    class SenderSubID:
        tag: int = 50

    # SendingDate(51): LOCALMKTDATE
    class SendingDate:
        tag: int = 51

    # SendingTime(52): UTCTIMESTAMP
    class SendingTime:
        tag: int = 52

    # Shares(53): QTY
    class Shares:
        tag: int = 53

    # Side(54): CHAR
    class Side:
        tag: int = 54
        BUY: str = '1'
        SELL: str = '2'
        BUY_MINUS: str = '3'
        SELL_PLUS: str = '4'
        SELL_SHORT: str = '5'
        SELL_SHORT_EXEMPT: str = '6'
        UNDISCLOSED: str = '7'
        CROSS: str = '8'
        CROSS_SHORT: str = '9'

    # Symbol(55): STRING
    class Symbol:
        tag: int = 55

    # TargetCompID(56): STRING
    class TargetCompID:
        tag: int = 56

    # TargetSubID(57): STRING
    class TargetSubID:
        tag: int = 57

    # Text(58): STRING
    class Text:
        tag: int = 58

    # TimeInForce(59): CHAR
    class TimeInForce:
        tag: int = 59
        DAY: str = '0'
        GOOD_TILL_CANCEL: str = '1'
        AT_THE_OPENING: str = '2'
        IMMEDIATE_OR_CANCEL: str = '3'
        FILL_OR_KILL: str = '4'
        GOOD_TILL_CROSSING: str = '5'
        GOOD_TILL_DATE: str = '6'

    # TransactTime(60): UTCTIMESTAMP
    class TransactTime:
        tag: int = 60

    # Urgency(61): CHAR
    class Urgency:
        tag: int = 61
        NORMAL: str = '0'
        FLASH: str = '1'
        BACKGROUND: str = '2'

    # ValidUntilTime(62): UTCTIMESTAMP
    class ValidUntilTime:
        tag: int = 62

    # SettlmntTyp(63): CHAR
    class SettlmntTyp:
        tag: int = 63
        REGULAR: str = '0'
        CASH: str = '1'
        NEXT_DAY: str = '2'
        T_PLUS_2: str = '3'
        T_PLUS_3: str = '4'
        T_PLUS_4: str = '5'
        FUTURE: str = '6'
        WHEN_ISSUED: str = '7'
        SELLERS_OPTION: str = '8'
        T_PLUS_5: str = '9'

    # FutSettDate(64): LOCALMKTDATE
    class FutSettDate:
        tag: int = 64

    # SymbolSfx(65): STRING
    class SymbolSfx:
        tag: int = 65

    # ListID(66): STRING
    class ListID:
        tag: int = 66

    # ListSeqNo(67): INT
    class ListSeqNo:
        tag: int = 67

    # TotNoOrders(68): INT
    class TotNoOrders:
        tag: int = 68

    # ListExecInst(69): STRING
    class ListExecInst:
        tag: int = 69

    # AllocID(70): STRING
    class AllocID:
        tag: int = 70

    # AllocTransType(71): CHAR
    class AllocTransType:
        tag: int = 71
        NEW: str = '0'
        REPLACE: str = '1'
        CANCEL: str = '2'
        PRELIMINARY: str = '3'
        CALCULATED: str = '4'
        CALCULATED_WITHOUT_PRELIMINARY: str = '5'

    # RefAllocID(72): STRING
    class RefAllocID:
        tag: int = 72

    # NoOrders(73): INT
    class NoOrders:
        tag: int = 73

    # AvgPrxPrecision(74): INT
    class AvgPrxPrecision:
        tag: int = 74

    # TradeDate(75): LOCALMKTDATE
    class TradeDate:
        tag: int = 75

    # ExecBroker(76): STRING
    class ExecBroker:
        tag: int = 76

    # OpenClose(77): CHAR
    class OpenClose:
        tag: int = 77
        CLOSE: str = 'C'
        OPEN: str = 'O'

    # NoAllocs(78): INT
    class NoAllocs:
        tag: int = 78

    # AllocAccount(79): STRING
    class AllocAccount:
        tag: int = 79

    # AllocShares(80): QTY
    class AllocShares:
        tag: int = 80

    # ProcessCode(81): CHAR
    class ProcessCode:
        tag: int = 81
        REGULAR: str = '0'
        SOFT_DOLLAR: str = '1'
        STEP_IN: str = '2'
        STEP_OUT: str = '3'
        SOFT_DOLLAR_STEP_IN: str = '4'
        SOFT_DOLLAR_STEP_OUT: str = '5'
        PLAN_SPONSOR: str = '6'

    # NoRpts(82): INT
    class NoRpts:
        tag: int = 82

    # RptSeq(83): INT
    class RptSeq:
        tag: int = 83

    # CxlQty(84): QTY
    class CxlQty:
        tag: int = 84

    # NoDlvyInst(85): INT
    class NoDlvyInst:
        tag: int = 85

    # DlvyInst(86): STRING
    class DlvyInst:
        tag: int = 86

    # AllocStatus(87): INT
    class AllocStatus:
        tag: int = 87
        ACCEPTED: int = 0
        REJECTED: int = 1
        PARTIAL_ACCEPT: int = 2
        RECEIVED: int = 3

    # AllocRejCode(88): INT
    class AllocRejCode:
        tag: int = 88
        UNKNOWN_ACCOUNT: int = 0
        INCORRECT_QUANTITY: int = 1
        INCORRECT_AVERAGE_PRICE: int = 2
        UNKNOWN_EXECUTING_BROKER_MNEMONIC: int = 3
        COMMISSION_DIFFERENCE: int = 4
        UNKNOWN_ORDERID: int = 5
        UNKNOWN_LISTID: int = 6
        OTHER: int = 7

    # Signature(89): DATA
    class Signature:
        tag: int = 89

    # SecureDataLen(90): LENGTH
    class SecureDataLen:
        tag: int = 90

    # SecureData(91): DATA
    class SecureData:
        tag: int = 91

    # BrokerOfCredit(92): STRING
    class BrokerOfCredit:
        tag: int = 92

    # SignatureLength(93): LENGTH
    class SignatureLength:
        tag: int = 93

    # EmailType(94): CHAR
    class EmailType:
        tag: int = 94
        NEW: str = '0'
        REPLY: str = '1'
        ADMIN_REPLY: str = '2'

    # RawDataLength(95): LENGTH
    class RawDataLength:
        tag: int = 95

    # RawData(96): DATA
    class RawData:
        tag: int = 96

    # PossResend(97): BOOLEAN
    class PossResend:
        tag: int = 97
        NO: str = 'N'
        YES: str = 'Y'

    # EncryptMethod(98): INT
    class EncryptMethod:
        tag: int = 98
        NONE: int = 0
        PKCS: int = 1
        DES: int = 2
        PKCS_DES: int = 3
        PGP_DES: int = 4
        PGP_DES_MD5: int = 5
        PEM_DES_MD5: int = 6

    # StopPx(99): PRICE
    class StopPx:
        tag: int = 99

    # ExDestination(100): EXCHANGE
    class ExDestination:
        tag: int = 100

    # CxlRejReason(102): INT
    class CxlRejReason:
        tag: int = 102
        TOO_LATE_TO_CANCEL: int = 0
        UNKNOWN_ORDER: int = 1
        BROKER_OPTION: int = 2
        ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS: int = 3

    # OrdRejReason(103): INT
    class OrdRejReason:
        tag: int = 103
        BROKER_OPTION: int = 0
        UNKNOWN_SYMBOL: int = 1
        EXCHANGE_CLOSED: int = 2
        ORDER_EXCEEDS_LIMIT: int = 3
        TOO_LATE_TO_ENTER: int = 4
        UNKNOWN_ORDER: int = 5
        DUPLICATE_ORDER: int = 6
        DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER: int = 7
        STALE_ORDER: int = 8

    # IOIQualifier(104): CHAR
    class IOIQualifier:
        tag: int = 104
        ALL_OR_NONE: str = 'A'
        AT_THE_CLOSE: str = 'C'
        IN_TOUCH_WITH: str = 'I'
        LIMIT: str = 'L'
        MORE_BEHIND: str = 'M'
        AT_THE_OPEN: str = 'O'
        TAKING_A_POSITION: str = 'P'
        AT_THE_MARKET: str = 'Q'
        READY_TO_TRADE: str = 'R'
        PORTFOLIO_SHOW_N: str = 'S'
        THROUGH_THE_DAY: str = 'T'
        VERSUS: str = 'V'
        INDICATION: str = 'W'
        CROSSING_OPPORTUNITY: str = 'X'
        AT_THE_MIDPOINT: str = 'Y'
        PRE_OPEN: str = 'Z'

    # WaveNo(105): STRING
    class WaveNo:
        tag: int = 105

    # Issuer(106): STRING
    class Issuer:
        tag: int = 106

    # SecurityDesc(107): STRING
    class SecurityDesc:
        tag: int = 107

    # HeartBtInt(108): INT
    class HeartBtInt:
        tag: int = 108

    # ClientID(109): STRING
    class ClientID:
        tag: int = 109

    # MinQty(110): QTY
    class MinQty:
        tag: int = 110

    # MaxFloor(111): QTY
    class MaxFloor:
        tag: int = 111

    # TestReqID(112): STRING
    class TestReqID:
        tag: int = 112

    # ReportToExch(113): BOOLEAN
    class ReportToExch:
        tag: int = 113
        NO: str = 'N'
        YES: str = 'Y'

    # LocateReqd(114): BOOLEAN
    class LocateReqd:
        tag: int = 114
        NO: str = 'N'
        YES: str = 'Y'

    # OnBehalfOfCompID(115): STRING
    class OnBehalfOfCompID:
        tag: int = 115

    # OnBehalfOfSubID(116): STRING
    class OnBehalfOfSubID:
        tag: int = 116

    # QuoteID(117): STRING
    class QuoteID:
        tag: int = 117

    # NetMoney(118): AMT
    class NetMoney:
        tag: int = 118

    # SettlCurrAmt(119): AMT
    class SettlCurrAmt:
        tag: int = 119

    # SettlCurrency(120): CURRENCY
    class SettlCurrency:
        tag: int = 120

    # ForexReq(121): BOOLEAN
    class ForexReq:
        tag: int = 121
        NO: str = 'N'
        YES: str = 'Y'

    # OrigSendingTime(122): UTCTIMESTAMP
    class OrigSendingTime:
        tag: int = 122

    # GapFillFlag(123): BOOLEAN
    class GapFillFlag:
        tag: int = 123
        NO: str = 'N'
        YES: str = 'Y'

    # NoExecs(124): INT
    class NoExecs:
        tag: int = 124

    # CxlType(125):  CHAR
    class CxlType:
        tag: int = 125

    # ExpireTime(126): UTCTIMESTAMP
    class ExpireTime:
        tag: int = 126

    # DKReason(127): CHAR
    class DKReason:
        tag: int = 127
        UNKNOWN_SYMBOL: str = 'A'
        WRONG_SIDE: str = 'B'
        QUANTITY_EXCEEDS_ORDER: str = 'C'
        NO_MATCHING_ORDER: str = 'D'
        PRICE_EXCEEDS_LIMIT: str = 'E'
        OTHER: str = 'Z'

    # DeliverToCompID(128): STRING
    class DeliverToCompID:
        tag: int = 128

    # DeliverToSubID(129): STRING
    class DeliverToSubID:
        tag: int = 129

    # IOINaturalFlag(130): BOOLEAN
    class IOINaturalFlag:
        tag: int = 130
        NO: str = 'N'
        YES: str = 'Y'

    # QuoteReqID(131): STRING
    class QuoteReqID:
        tag: int = 131

    # BidPx(132): PRICE
    class BidPx:
        tag: int = 132

    # OfferPx(133): PRICE
    class OfferPx:
        tag: int = 133

    # BidSize(134): QTY
    class BidSize:
        tag: int = 134

    # OfferSize(135): QTY
    class OfferSize:
        tag: int = 135

    # NoMiscFees(136): INT
    class NoMiscFees:
        tag: int = 136

    # MiscFeeAmt(137): AMT
    class MiscFeeAmt:
        tag: int = 137

    # MiscFeeCurr(138): CURRENCY
    class MiscFeeCurr:
        tag: int = 138

    # MiscFeeType(139): CHAR
    class MiscFeeType:
        tag: int = 139
        REGULATORY: str = '1'
        TAX: str = '2'
        LOCAL_COMMISSION: str = '3'
        EXCHANGE_FEES: str = '4'
        STAMP: str = '5'
        LEVY: str = '6'
        OTHER: str = '7'
        MARKUP: str = '8'
        CONSUMPTION_TAX: str = '9'

    # PrevClosePx(140): PRICE
    class PrevClosePx:
        tag: int = 140

    # ResetSeqNumFlag(141): BOOLEAN
    class ResetSeqNumFlag:
        tag: int = 141
        NO: str = 'N'
        YES: str = 'Y'

    # SenderLocationID(142): STRING
    class SenderLocationID:
        tag: int = 142

    # TargetLocationID(143): STRING
    class TargetLocationID:
        tag: int = 143

    # OnBehalfOfLocationID(144): STRING
    class OnBehalfOfLocationID:
        tag: int = 144

    # DeliverToLocationID(145): STRING
    class DeliverToLocationID:
        tag: int = 145

    # NoRelatedSym(146): INT
    class NoRelatedSym:
        tag: int = 146

    # Subject(147): STRING
    class Subject:
        tag: int = 147

    # Headline(148): STRING
    class Headline:
        tag: int = 148

    # URLLink(149): STRING
    class URLLink:
        tag: int = 149

    # ExecType(150): CHAR
    class ExecType:
        tag: int = 150
        NEW: str = '0'
        PARTIAL_FILL: str = '1'
        FILL: str = '2'
        DONE_FOR_DAY: str = '3'
        CANCELED: str = '4'
        REPLACE: str = '5'
        PENDING_CANCEL: str = '6'
        STOPPED: str = '7'
        REJECTED: str = '8'
        SUSPENDED: str = '9'
        PENDING_NEW: str = 'A'
        CALCULATED: str = 'B'
        EXPIRED: str = 'C'
        RESTATED: str = 'D'
        PENDING_REPLACE: str = 'E'

    # LeavesQty(151): QTY
    class LeavesQty:
        tag: int = 151

    # CashOrderQty(152): QTY
    class CashOrderQty:
        tag: int = 152

    # AllocAvgPx(153): PRICE
    class AllocAvgPx:
        tag: int = 153

    # AllocNetMoney(154): AMT
    class AllocNetMoney:
        tag: int = 154

    # SettlCurrFxRate(155): FLOAT
    class SettlCurrFxRate:
        tag: int = 155

    # SettlCurrFxRateCalc(156): CHAR
    class SettlCurrFxRateCalc:
        tag: int = 156
        MULTIPLY: str = 'M'
        DIVIDE: str = 'D'

    # NumDaysInterest(157): INT
    class NumDaysInterest:
        tag: int = 157

    # AccruedInterestRate(158): FLOAT
    class AccruedInterestRate:
        tag: int = 158

    # AccruedInterestAmt(159): AMT
    class AccruedInterestAmt:
        tag: int = 159

    # SettlInstMode(160): CHAR
    class SettlInstMode:
        tag: int = 160
        DEFAULT: str = '0'
        STANDING_INSTRUCTIONS_PROVIDED: str = '1'
        SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING: str = '2'
        SPECIFIC_ALLOCATION_ACCOUNT_STANDING: str = '3'

    # AllocText(161): STRING
    class AllocText:
        tag: int = 161

    # SettlInstID(162): STRING
    class SettlInstID:
        tag: int = 162

    # SettlInstTransType(163): CHAR
    class SettlInstTransType:
        tag: int = 163
        CANCEL: str = 'C'
        NEW: str = 'N'
        REPLACE: str = 'R'

    # EmailThreadID(164): STRING
    class EmailThreadID:
        tag: int = 164

    # SettlInstSource(165): CHAR
    class SettlInstSource:
        tag: int = 165
        BROKERS_INSTRUCTIONS: str = '1'
        INSTITUTIONS_INSTRUCTIONS: str = '2'

    # SettlLocation(166): STRING
    class SettlLocation:
        tag: int = 166
        CEDEL: str = "CED"
        DEPOSITORY_TRUST_COMPANY: str = "DTC"
        EUROCLEAR: str = "EUR"
        FEDERAL_BOOK_ENTRY: str = "FED"
        LOCAL_MARKET_SETTLE_LOCATION: str = "ISO Country Code"
        PHYSICAL: str = "PNY"
        PARTICIPANT_TRUST_COMPANY: str = "PTC"

    # SecurityType(167): STRING
    class SecurityType:
        tag: int = 167
        WILDCARD_ENTRY: str = "?"
        BANKERS_ACCEPTANCE: str = "BA"
        CONVERTIBLE_BOND: str = "CB"
        CERTIFICATE_OF_DEPOSIT: str = "CD"
        COLLATERALIZE_MORTGAGE_OBLIGATION: str = "CMO"
        CORPORATE_BOND: str = "CORP"
        COMMERCIAL_PAPER: str = "CP"
        CORPORATE_PRIVATE_PLACEMENT: str = "CPP"
        COMMON_STOCK: str = "CS"
        FEDERAL_HOUSING_AUTHORITY: str = "FHA"
        FEDERAL_HOME_LOAN: str = "FHL"
        FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION: str = "FN"
        FOREIGN_EXCHANGE_CONTRACT: str = "FOR"
        FUTURE: str = "FUT"
        GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION: str = "GN"
        TREASURIES_PLUS_AGENCY_DEBENTURE: str = "GOVT"
        MORTGAGE_IOETTE: str = "IET"
        MUTUAL_FUND: str = "MF"
        MORTGAGE_INTEREST_ONLY: str = "MIO"
        MORTGAGE_PRINCIPAL_ONLY: str = "MPO"
        MORTGAGE_PRIVATE_PLACEMENT: str = "MPP"
        MISCELLANEOUS_PASS_THRU: str = "MPT"
        MUNICIPAL_BOND: str = "MUNI"
        NO_ISITC_SECURITY_TYPE: str = "NONE"
        OPTION: str = "OPT"
        PREFERRED_STOCK: str = "PS"
        REPURCHASE_AGREEMENT: str = "RP"
        REVERSE_REPURCHASE_AGREEMENT: str = "RVRP"
        STUDENT_LOAN_MARKETING_ASSOCIATION: str = "SL"
        TIME_DEPOSIT: str = "TD"
        US_TREASURY_BILL: str = "USTB"
        WARRANT: str = "WAR"
        CATS_TIGERS_LIONS: str = "ZOO"

    # EffectiveTime(168): UTCTIMESTAMP
    class EffectiveTime:
        tag: int = 168

    # StandInstDbType(169): INT
    class StandInstDbType:
        tag: int = 169
        OTHER: int = 0
        DTC_SID: int = 1
        THOMSON_ALERT: int = 2
        A_GLOBAL_CUSTODIAN: int = 3

    # StandInstDbName(170): STRING
    class StandInstDbName:
        tag: int = 170

    # StandInstDbID(171): STRING
    class StandInstDbID:
        tag: int = 171

    # SettlDeliveryType(172): INT
    class SettlDeliveryType:
        tag: int = 172

    # SettlDepositoryCode(173): STRING
    class SettlDepositoryCode:
        tag: int = 173

    # SettlBrkrCode(174): STRING
    class SettlBrkrCode:
        tag: int = 174

    # SettlInstCode(175): STRING
    class SettlInstCode:
        tag: int = 175

    # SecuritySettlAgentName(176): STRING
    class SecuritySettlAgentName:
        tag: int = 176

    # SecuritySettlAgentCode(177): STRING
    class SecuritySettlAgentCode:
        tag: int = 177

    # SecuritySettlAgentAcctNum(178): STRING
    class SecuritySettlAgentAcctNum:
        tag: int = 178

    # SecuritySettlAgentAcctName(179): STRING
    class SecuritySettlAgentAcctName:
        tag: int = 179

    # SecuritySettlAgentContactName(180): STRING
    class SecuritySettlAgentContactName:
        tag: int = 180

    # SecuritySettlAgentContactPhone(181): STRING
    class SecuritySettlAgentContactPhone:
        tag: int = 181

    # CashSettlAgentName(182): STRING
    class CashSettlAgentName:
        tag: int = 182

    # CashSettlAgentCode(183): STRING
    class CashSettlAgentCode:
        tag: int = 183

    # CashSettlAgentAcctNum(184): STRING
    class CashSettlAgentAcctNum:
        tag: int = 184

    # CashSettlAgentAcctName(185): STRING
    class CashSettlAgentAcctName:
        tag: int = 185

    # CashSettlAgentContactName(186): STRING
    class CashSettlAgentContactName:
        tag: int = 186

    # CashSettlAgentContactPhone(187): STRING
    class CashSettlAgentContactPhone:
        tag: int = 187

    # BidSpotRate(188): PRICE
    class BidSpotRate:
        tag: int = 188

    # BidForwardPoints(189): PRICEOFFSET
    class BidForwardPoints:
        tag: int = 189

    # OfferSpotRate(190): PRICE
    class OfferSpotRate:
        tag: int = 190

    # OfferForwardPoints(191): PRICEOFFSET
    class OfferForwardPoints:
        tag: int = 191

    # OrderQty2(192): QTY
    class OrderQty2:
        tag: int = 192

    # FutSettDate2(193): LOCALMKTDATE
    class FutSettDate2:
        tag: int = 193

    # LastSpotRate(194): PRICE
    class LastSpotRate:
        tag: int = 194

    # LastForwardPoints(195): PRICEOFFSET
    class LastForwardPoints:
        tag: int = 195

    # AllocLinkID(196): STRING
    class AllocLinkID:
        tag: int = 196

    # AllocLinkType(197): INT
    class AllocLinkType:
        tag: int = 197
        F_X_NETTING: int = 0
        F_X_SWAP: int = 1

    # SecondaryOrderID(198): STRING
    class SecondaryOrderID:
        tag: int = 198

    # NoIOIQualifiers(199): INT
    class NoIOIQualifiers:
        tag: int = 199

    # MaturityMonthYear(200): MONTHYEAR
    class MaturityMonthYear:
        tag: int = 200

    # PutOrCall(201): INT
    class PutOrCall:
        tag: int = 201
        PUT: int = 0
        CALL: int = 1

    # StrikePrice(202): PRICE
    class StrikePrice:
        tag: int = 202

    # CoveredOrUncovered(203): INT
    class CoveredOrUncovered:
        tag: int = 203
        COVERED: int = 0
        UNCOVERED: int = 1

    # CustomerOrFirm(204): INT
    class CustomerOrFirm:
        tag: int = 204
        CUSTOMER: int = 0
        FIRM: int = 1

    # MaturityDay(205): DAYOFMONTH
    class MaturityDay:
        tag: int = 205

    # OptAttribute(206): CHAR
    class OptAttribute:
        tag: int = 206

    # SecurityExchange(207): EXCHANGE
    class SecurityExchange:
        tag: int = 207

    # NotifyBrokerOfCredit(208): BOOLEAN
    class NotifyBrokerOfCredit:
        tag: int = 208
        NO: str = 'N'
        YES: str = 'Y'

    # AllocHandlInst(209): INT
    class AllocHandlInst:
        tag: int = 209
        MATCH: int = 1
        FORWARD: int = 2
        FORWARD_AND_MATCH: int = 3

    # MaxShow(210): QTY
    class MaxShow:
        tag: int = 210

    # PegDifference(211): PRICEOFFSET
    class PegDifference:
        tag: int = 211

    # XmlDataLen(212): LENGTH
    class XmlDataLen:
        tag: int = 212

    # XmlData(213): DATA
    class XmlData:
        tag: int = 213

    # SettlInstRefID(214): STRING
    class SettlInstRefID:
        tag: int = 214

    # NoRoutingIDs(215): INT
    class NoRoutingIDs:
        tag: int = 215

    # RoutingType(216): INT
    class RoutingType:
        tag: int = 216
        TARGET_FIRM: int = 1
        TARGET_LIST: int = 2
        BLOCK_FIRM: int = 3
        BLOCK_LIST: int = 4

    # RoutingID(217): STRING
    class RoutingID:
        tag: int = 217

    # SpreadToBenchmark(218): PRICEOFFSET
    class SpreadToBenchmark:
        tag: int = 218

    # Benchmark(219): CHAR
    class Benchmark:
        tag: int = 219
        CURVE: str = '1'
        _5_YR: str = '2'
        OLD_5: str = '3'
        _10_YR: str = '4'
        OLD_10: str = '5'
        _30_YR: str = '6'
        OLD_30: str = '7'
        _3_MO_LIBOR: str = '8'
        _6_MO_LIBOR: str = '9'

    # CouponRate(223): FLOAT
    class CouponRate:
        tag: int = 223

    # ContractMultiplier(231): FLOAT
    class ContractMultiplier:
        tag: int = 231

    # MDReqID(262): STRING
    class MDReqID:
        tag: int = 262

    # SubscriptionRequestType(263): CHAR
    class SubscriptionRequestType:
        tag: int = 263
        SNAPSHOT: str = '0'
        SNAPSHOT_PLUS_UPDATES: str = '1'
        DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST: str = '2'

    # MarketDepth(264): INT
    class MarketDepth:
        tag: int = 264

    # MDUpdateType(265): INT
    class MDUpdateType:
        tag: int = 265
        FULL_REFRESH: int = 0
        INCREMENTAL_REFRESH: int = 1

    # AggregatedBook(266): BOOLEAN
    class AggregatedBook:
        tag: int = 266
        NO: str = 'N'
        YES: str = 'Y'

    # NoMDEntryTypes(267): INT
    class NoMDEntryTypes:
        tag: int = 267

    # NoMDEntries(268): INT
    class NoMDEntries:
        tag: int = 268

    # MDEntryType(269): CHAR
    class MDEntryType:
        tag: int = 269
        BID: str = '0'
        OFFER: str = '1'
        TRADE: str = '2'
        INDEX_VALUE: str = '3'
        OPENING_PRICE: str = '4'
        CLOSING_PRICE: str = '5'
        SETTLEMENT_PRICE: str = '6'
        TRADING_SESSION_HIGH_PRICE: str = '7'
        TRADING_SESSION_LOW_PRICE: str = '8'
        TRADING_SESSION_VWAP_PRICE: str = '9'

    # MDEntryPx(270): PRICE
    class MDEntryPx:
        tag: int = 270

    # MDEntrySize(271): QTY
    class MDEntrySize:
        tag: int = 271

    # MDEntryDate(272): UTCDATE
    class MDEntryDate:
        tag: int = 272

    # MDEntryTime(273): UTCTIMEONLY
    class MDEntryTime:
        tag: int = 273

    # TickDirection(274): CHAR
    class TickDirection:
        tag: int = 274
        PLUS_TICK: str = '0'
        ZERO_PLUS_TICK: str = '1'
        MINUS_TICK: str = '2'
        ZERO_MINUS_TICK: str = '3'

    # MDMkt(275): EXCHANGE
    class MDMkt:
        tag: int = 275

    # QuoteCondition(276): MULTIPLEVALUESTRING
    class QuoteCondition:
        tag: int = 276
        OPEN: str = "A"
        CLOSED: str = "B"
        EXCHANGE_BEST: str = "C"
        CONSOLIDATED_BEST: str = "D"
        LOCKED: str = "E"
        CROSSED: str = "F"
        DEPTH: str = "G"
        FAST_TRADING: str = "H"
        NON_FIRM: str = "I"

    # TradeCondition(277): MULTIPLEVALUESTRING
    class TradeCondition:
        tag: int = 277
        CASH: str = "A"
        AVERAGE_PRICE_TRADE: str = "B"
        CASH_TRADE: str = "C"
        NEXT_DAY: str = "D"
        OPENING: str = "E"
        INTRADAY_TRADE_DETAIL: str = "F"
        RULE_127_TRADE: str = "G"
        RULE_155_TRADE: str = "H"
        SOLD_LAST: str = "I"
        NEXT_DAY_TRADE: str = "J"
        OPENED: str = "K"
        SELLER: str = "L"
        SOLD: str = "M"
        STOPPED_STOCK: str = "N"

    # MDEntryID(278): STRING
    class MDEntryID:
        tag: int = 278

    # MDUpdateAction(279): CHAR
    class MDUpdateAction:
        tag: int = 279
        NEW: str = '0'
        CHANGE: str = '1'
        DELETE: str = '2'

    # MDEntryRefID(280): STRING
    class MDEntryRefID:
        tag: int = 280

    # MDReqRejReason(281): CHAR
    class MDReqRejReason:
        tag: int = 281
        UNKNOWN_SYMBOL: str = '0'
        DUPLICATE_MDREQID: str = '1'
        INSUFFICIENT_BANDWIDTH: str = '2'
        INSUFFICIENT_PERMISSIONS: str = '3'
        UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE: str = '4'
        UNSUPPORTED_MARKETDEPTH: str = '5'
        UNSUPPORTED_MDUPDATETYPE: str = '6'
        UNSUPPORTED_AGGREGATEDBOOK: str = '7'
        UNSUPPORTED_MDENTRYTYPE: str = '8'

    # MDEntryOriginator(282): STRING
    class MDEntryOriginator:
        tag: int = 282

    # LocationID(283): STRING
    class LocationID:
        tag: int = 283

    # DeskID(284): STRING
    class DeskID:
        tag: int = 284

    # DeleteReason(285): CHAR
    class DeleteReason:
        tag: int = 285
        CANCELATION: str = '0'
        ERROR: str = '1'

    # OpenCloseSettleFlag(286): CHAR
    class OpenCloseSettleFlag:
        tag: int = 286
        DAILY_OPEN: str = '0'
        SESSION_OPEN: str = '1'
        DELIVERY_SETTLEMENT_PRICE: str = '2'

    # SellerDays(287): INT
    class SellerDays:
        tag: int = 287

    # MDEntryBuyer(288): STRING
    class MDEntryBuyer:
        tag: int = 288

    # MDEntrySeller(289): STRING
    class MDEntrySeller:
        tag: int = 289

    # MDEntryPositionNo(290): INT
    class MDEntryPositionNo:
        tag: int = 290

    # FinancialStatus(291): CHAR
    class FinancialStatus:
        tag: int = 291
        BANKRUPT: str = '1'

    # CorporateAction(292): CHAR
    class CorporateAction:
        tag: int = 292
        EX_DIVIDEND: str = 'A'
        EX_DISTRIBUTION: str = 'B'
        EX_RIGHTS: str = 'C'
        NEW: str = 'D'
        EX_INTEREST: str = 'E'

    # DefBidSize(293): QTY
    class DefBidSize:
        tag: int = 293

    # DefOfferSize(294): QTY
    class DefOfferSize:
        tag: int = 294

    # NoQuoteEntries(295): INT
    class NoQuoteEntries:
        tag: int = 295

    # NoQuoteSets(296): INT
    class NoQuoteSets:
        tag: int = 296

    # QuoteAckStatus(297): INT
    class QuoteAckStatus:
        tag: int = 297
        ACCEPTED: int = 0
        CANCELED_FOR_SYMBOL: int = 1
        CANCELED_FOR_SECURITY_TYPE: int = 2
        CANCELED_FOR_UNDERLYING: int = 3
        CANCELED_ALL: int = 4
        REJECTED: int = 5

    # QuoteCancelType(298): INT
    class QuoteCancelType:
        tag: int = 298
        CANCEL_FOR_SYMBOL: int = 1
        CANCEL_FOR_SECURITY_TYPE: int = 2
        CANCEL_FOR_UNDERLYING_SYMBOL: int = 3
        CANCEL_FOR_ALL_QUOTES: int = 4

    # QuoteEntryID(299): STRING
    class QuoteEntryID:
        tag: int = 299

    # QuoteRejectReason(300): INT
    class QuoteRejectReason:
        tag: int = 300
        UNKNOWN_SYMBOL: int = 1
        EXCHANGE: int = 2
        QUOTE_REQUEST_EXCEEDS_LIMIT: int = 3
        TOO_LATE_TO_ENTER: int = 4
        UNKNOWN_QUOTE: int = 5
        DUPLICATE_QUOTE: int = 6
        INVALID_BID_ASK_SPREAD: int = 7
        INVALID_PRICE: int = 8
        NOT_AUTHORIZED_TO_QUOTE_SECURITY: int = 9

    # QuoteResponseLevel(301): INT
    class QuoteResponseLevel:
        tag: int = 301
        NO_ACKNOWLEDGEMENT: int = 0
        ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES: int = 1
        ACKNOWLEDGE_EACH_QUOTE_MESSAGES: int = 2

    # QuoteSetID(302): STRING
    class QuoteSetID:
        tag: int = 302

    # QuoteRequestType(303): INT
    class QuoteRequestType:
        tag: int = 303
        MANUAL: int = 1
        AUTOMATIC: int = 2

    # TotQuoteEntries(304): INT
    class TotQuoteEntries:
        tag: int = 304

    # UnderlyingIDSource(305): STRING
    class UnderlyingIDSource:
        tag: int = 305

    # UnderlyingIssuer(306): STRING
    class UnderlyingIssuer:
        tag: int = 306

    # UnderlyingSecurityDesc(307): STRING
    class UnderlyingSecurityDesc:
        tag: int = 307

    # UnderlyingSecurityExchange(308): EXCHANGE
    class UnderlyingSecurityExchange:
        tag: int = 308

    # UnderlyingSecurityID(309): STRING
    class UnderlyingSecurityID:
        tag: int = 309

    # UnderlyingSecurityType(310): STRING
    class UnderlyingSecurityType:
        tag: int = 310

    # UnderlyingSymbol(311): STRING
    class UnderlyingSymbol:
        tag: int = 311

    # UnderlyingSymbolSfx(312): STRING
    class UnderlyingSymbolSfx:
        tag: int = 312

    # UnderlyingMaturityMonthYear(313): MONTHYEAR
    class UnderlyingMaturityMonthYear:
        tag: int = 313

    # UnderlyingMaturityDay(314): DAYOFMONTH
    class UnderlyingMaturityDay:
        tag: int = 314

    # UnderlyingPutOrCall(315): INT
    class UnderlyingPutOrCall:
        tag: int = 315

    # UnderlyingStrikePrice(316): PRICE
    class UnderlyingStrikePrice:
        tag: int = 316

    # UnderlyingOptAttribute(317): CHAR
    class UnderlyingOptAttribute:
        tag: int = 317

    # UnderlyingCurrency(318): CURRENCY
    class UnderlyingCurrency:
        tag: int = 318

    # RatioQty(319): QUANTITY
    class RatioQty:
        tag: int = 319

    # SecurityReqID(320): STRING
    class SecurityReqID:
        tag: int = 320

    # SecurityRequestType(321): INT
    class SecurityRequestType:
        tag: int = 321
        REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS: int = 0
        REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED: int = 1
        REQUEST_LIST_SECURITY_TYPES: int = 2
        REQUEST_LIST_SECURITIES: int = 3

    # SecurityResponseID(322): STRING
    class SecurityResponseID:
        tag: int = 322

    # SecurityResponseType(323): INT
    class SecurityResponseType:
        tag: int = 323
        ACCEPT_SECURITY_PROPOSAL_AS_IS: int = 1
        ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE: int = 2
        LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST: int = 3
        LIST_OF_SECURITIES_RETURNED_PER_REQUEST: int = 4
        REJECT_SECURITY_PROPOSAL: int = 5
        CAN_NOT_MATCH_SELECTION_CRITERIA: int = 6

    # SecurityStatusReqID(324): STRING
    class SecurityStatusReqID:
        tag: int = 324

    # UnsolicitedIndicator(325): BOOLEAN
    class UnsolicitedIndicator:
        tag: int = 325
        NO: str = 'N'
        YES: str = 'Y'

    # SecurityTradingStatus(326): INT
    class SecurityTradingStatus:
        tag: int = 326
        OPENING_DELAY: int = 1
        MARKET_ON_CLOSE_IMBALANCE_SELL: int = 10
        _11: int = 11
        NO_MARKET_IMBALANCE: int = 12
        NO_MARKET_ON_CLOSE_IMBALANCE: int = 13
        ITS_PRE_OPENING: int = 14
        NEW_PRICE_INDICATION: int = 15
        TRADE_DISSEMINATION_TIME: int = 16
        READY_TO_TRADE: int = 17
        NOT_AVAILABLE_FOR_TRADING: int = 18
        NOT_TRADED_ON_THIS_MARKET: int = 19
        TRADING_HALT: int = 2
        UNKNOWN_OR_INVALID: int = 20
        RESUME: int = 3
        NO_OPEN_NO_RESUME: int = 4
        PRICE_INDICATION: int = 5
        TRADING_RANGE_INDICATION: int = 6
        MARKET_IMBALANCE_BUY: int = 7
        MARKET_IMBALANCE_SELL: int = 8
        MARKET_ON_CLOSE_IMBALANCE_BUY: int = 9

    # HaltReasonChar(327): CHAR
    class HaltReasonChar:
        tag: int = 327
        NEWS_DISSEMINATION: str = 'D'
        ORDER_INFLUX: str = 'E'
        ORDER_IMBALANCE: str = 'I'
        ADDITIONAL_INFORMATION: str = 'M'
        NEWS_PENDING: str = 'P'
        EQUIPMENT_CHANGEOVER: str = 'X'

    # InViewOfCommon(328): BOOLEAN
    class InViewOfCommon:
        tag: int = 328
        NO: str = 'N'
        YES: str = 'Y'

    # DueToRelated(329): BOOLEAN
    class DueToRelated:
        tag: int = 329
        NO: str = 'N'
        YES: str = 'Y'

    # BuyVolume(330): QTY
    class BuyVolume:
        tag: int = 330

    # SellVolume(331): QTY
    class SellVolume:
        tag: int = 331

    # HighPx(332): PRICE
    class HighPx:
        tag: int = 332

    # LowPx(333): PRICE
    class LowPx:
        tag: int = 333

    # Adjustment(334): INT
    class Adjustment:
        tag: int = 334
        CANCEL: int = 1
        ERROR: int = 2
        CORRECTION: int = 3

    # TradSesReqID(335): STRING
    class TradSesReqID:
        tag: int = 335

    # TradingSessionID(336): STRING
    class TradingSessionID:
        tag: int = 336

    # ContraTrader(337): STRING
    class ContraTrader:
        tag: int = 337

    # TradSesMethod(338): INT
    class TradSesMethod:
        tag: int = 338
        ELECTRONIC: int = 1
        OPEN_OUTCRY: int = 2
        TWO_PARTY: int = 3

    # TradSesMode(339): INT
    class TradSesMode:
        tag: int = 339
        TESTING: int = 1
        SIMULATED: int = 2
        PRODUCTION: int = 3

    # TradSesStatus(340): INT
    class TradSesStatus:
        tag: int = 340
        HALTED: int = 1
        OPEN: int = 2
        CLOSED: int = 3
        PRE_OPEN: int = 4
        PRE_CLOSE: int = 5

    # TradSesStartTime(341): UTCTIMESTAMP
    class TradSesStartTime:
        tag: int = 341

    # TradSesOpenTime(342): UTCTIMESTAMP
    class TradSesOpenTime:
        tag: int = 342

    # TradSesPreCloseTime(343): UTCTIMESTAMP
    class TradSesPreCloseTime:
        tag: int = 343

    # TradSesCloseTime(344): UTCTIMESTAMP
    class TradSesCloseTime:
        tag: int = 344

    # TradSesEndTime(345): UTCTIMESTAMP
    class TradSesEndTime:
        tag: int = 345

    # NumberOfOrders(346): INT
    class NumberOfOrders:
        tag: int = 346

    # MessageEncoding(347): STRING
    class MessageEncoding:
        tag: int = 347
        EUC_JP: str = "EUC-JP"
        ISO_2022_JP: str = "ISO-2022-JP"
        SHIFT_JIS: str = "SHIFT_JIS"
        UTF_8: str = "UTF-8"

    # EncodedIssuerLen(348): LENGTH
    class EncodedIssuerLen:
        tag: int = 348

    # EncodedIssuer(349): DATA
    class EncodedIssuer:
        tag: int = 349

    # EncodedSecurityDescLen(350): LENGTH
    class EncodedSecurityDescLen:
        tag: int = 350

    # EncodedSecurityDesc(351): DATA
    class EncodedSecurityDesc:
        tag: int = 351

    # EncodedListExecInstLen(352): LENGTH
    class EncodedListExecInstLen:
        tag: int = 352

    # EncodedListExecInst(353): DATA
    class EncodedListExecInst:
        tag: int = 353

    # EncodedTextLen(354): LENGTH
    class EncodedTextLen:
        tag: int = 354

    # EncodedText(355): DATA
    class EncodedText:
        tag: int = 355

    # EncodedSubjectLen(356): LENGTH
    class EncodedSubjectLen:
        tag: int = 356

    # EncodedSubject(357): DATA
    class EncodedSubject:
        tag: int = 357

    # EncodedHeadlineLen(358): LENGTH
    class EncodedHeadlineLen:
        tag: int = 358

    # EncodedHeadline(359): DATA
    class EncodedHeadline:
        tag: int = 359

    # EncodedAllocTextLen(360): LENGTH
    class EncodedAllocTextLen:
        tag: int = 360

    # EncodedAllocText(361): DATA
    class EncodedAllocText:
        tag: int = 361

    # EncodedUnderlyingIssuerLen(362): LENGTH
    class EncodedUnderlyingIssuerLen:
        tag: int = 362

    # EncodedUnderlyingIssuer(363): DATA
    class EncodedUnderlyingIssuer:
        tag: int = 363

    # EncodedUnderlyingSecurityDescLen(364): LENGTH
    class EncodedUnderlyingSecurityDescLen:
        tag: int = 364

    # EncodedUnderlyingSecurityDesc(365): DATA
    class EncodedUnderlyingSecurityDesc:
        tag: int = 365

    # AllocPrice(366): PRICE
    class AllocPrice:
        tag: int = 366

    # QuoteSetValidUntilTime(367): UTCTIMESTAMP
    class QuoteSetValidUntilTime:
        tag: int = 367

    # QuoteEntryRejectReason(368): INT
    class QuoteEntryRejectReason:
        tag: int = 368
        UNKNOWN_SYMBOL: int = 1
        EXCHANGE: int = 2
        QUOTE_EXCEEDS_LIMIT: int = 3
        TOO_LATE_TO_ENTER: int = 4
        UNKNOWN_QUOTE: int = 5
        DUPLICATE_QUOTE: int = 6
        INVALID_BID_ASK_SPREAD: int = 7
        INVALID_PRICE: int = 8
        NOT_AUTHORIZED_TO_QUOTE_SECURITY: int = 9

    # LastMsgSeqNumProcessed(369): INT
    class LastMsgSeqNumProcessed:
        tag: int = 369

    # OnBehalfOfSendingTime(370): UTCTIMESTAMP
    class OnBehalfOfSendingTime:
        tag: int = 370

    # RefTagID(371): INT
    class RefTagID:
        tag: int = 371

    # RefMsgType(372): STRING
    class RefMsgType:
        tag: int = 372

    # SessionRejectReason(373): INT
    class SessionRejectReason:
        tag: int = 373
        INVALID_TAG_NUMBER: int = 0
        REQUIRED_TAG_MISSING: int = 1
        SENDINGTIME_ACCURACY_PROBLEM: int = 10
        INVALID_MSGTYPE: int = 11
        TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE: int = 2
        UNDEFINED_TAG: int = 3
        TAG_SPECIFIED_WITHOUT_A_VALUE: int = 4
        VALUE_IS_INCORRECT: int = 5
        INCORRECT_DATA_FORMAT_FOR_VALUE: int = 6
        DECRYPTION_PROBLEM: int = 7
        SIGNATURE_PROBLEM: int = 8
        COMPID_PROBLEM: int = 9

    # BidRequestTransType(374): CHAR
    class BidRequestTransType:
        tag: int = 374
        CANCEL: str = 'C'
        NO: str = 'N'

    # ContraBroker(375): STRING
    class ContraBroker:
        tag: int = 375

    # ComplianceID(376): STRING
    class ComplianceID:
        tag: int = 376

    # SolicitedFlag(377): BOOLEAN
    class SolicitedFlag:
        tag: int = 377
        NO: str = 'N'
        YES: str = 'Y'

    # ExecRestatementReason(378): INT
    class ExecRestatementReason:
        tag: int = 378
        GT_CORPORATE_ACTION: int = 0
        GT_RENEWAL: int = 1
        VERBAL_CHANGE: int = 2
        REPRICING_OF_ORDER: int = 3
        BROKER_OPTION: int = 4
        PARTIAL_DECLINE_OF_ORDERQTY: int = 5

    # BusinessRejectRefID(379): STRING
    class BusinessRejectRefID:
        tag: int = 379

    # BusinessRejectReason(380): INT
    class BusinessRejectReason:
        tag: int = 380
        OTHER: int = 0
        UNKOWN_ID: int = 1
        UNKNOWN_SECURITY: int = 2
        UNSUPPORTED_MESSAGE_TYPE: int = 3
        APPLICATION_NOT_AVAILABLE: int = 4
        CONDITIONALLY_REQUIRED_FIELD_MISSING: int = 5

    # GrossTradeAmt(381): AMT
    class GrossTradeAmt:
        tag: int = 381

    # NoContraBrokers(382): INT
    class NoContraBrokers:
        tag: int = 382

    # MaxMessageSize(383): INT
    class MaxMessageSize:
        tag: int = 383

    # NoMsgTypes(384): INT
    class NoMsgTypes:
        tag: int = 384

    # MsgDirection(385): CHAR
    class MsgDirection:
        tag: int = 385
        RECEIVE: str = 'R'
        SEND: str = 'S'

    # NoTradingSessions(386): INT
    class NoTradingSessions:
        tag: int = 386

    # TotalVolumeTraded(387): QTY
    class TotalVolumeTraded:
        tag: int = 387

    # DiscretionInst(388): CHAR
    class DiscretionInst:
        tag: int = 388
        RELATED_TO_DISPLAYED_PRICE: str = '0'
        RELATED_TO_MARKET_PRICE: str = '1'
        RELATED_TO_PRIMARY_PRICE: str = '2'
        RELATED_TO_LOCAL_PRIMARY_PRICE: str = '3'
        RELATED_TO_MIDPOINT_PRICE: str = '4'
        RELATED_TO_LAST_TRADE_PRICE: str = '5'

    # DiscretionOffset(389): PRICEOFFSET
    class DiscretionOffset:
        tag: int = 389

    # BidID(390): STRING
    class BidID:
        tag: int = 390

    # ClientBidID(391): STRING
    class ClientBidID:
        tag: int = 391

    # ListName(392): STRING
    class ListName:
        tag: int = 392

    # TotalNumSecurities(393): INT
    class TotalNumSecurities:
        tag: int = 393

    # BidType(394): INT
    class BidType:
        tag: int = 394

    # NumTickets(395): INT
    class NumTickets:
        tag: int = 395

    # SideValue1(396): AMT
    class SideValue1:
        tag: int = 396

    # SideValue2(397): AMT
    class SideValue2:
        tag: int = 397

    # NoBidDescriptors(398): INT
    class NoBidDescriptors:
        tag: int = 398

    # BidDescriptorType(399): INT
    class BidDescriptorType:
        tag: int = 399

    # BidDescriptor(400): STRING
    class BidDescriptor:
        tag: int = 400

    # SideValueInd(401): INT
    class SideValueInd:
        tag: int = 401

    # LiquidityPctLow(402): FLOAT
    class LiquidityPctLow:
        tag: int = 402

    # LiquidityPctHigh(403): FLOAT
    class LiquidityPctHigh:
        tag: int = 403

    # LiquidityValue(404): AMT
    class LiquidityValue:
        tag: int = 404

    # EFPTrackingError(405): FLOAT
    class EFPTrackingError:
        tag: int = 405

    # FairValue(406): AMT
    class FairValue:
        tag: int = 406

    # OutsideIndexPct(407): FLOAT
    class OutsideIndexPct:
        tag: int = 407

    # ValueOfFutures(408): AMT
    class ValueOfFutures:
        tag: int = 408

    # LiquidityIndType(409): INT
    class LiquidityIndType:
        tag: int = 409
        _5_DAY_MOVING_AVERAGE: int = 1
        _20_DAY_MOVING_AVERAGE: int = 2
        NORMAL_MARKET_SIZE: int = 3
        OTHER: int = 4

    # WtAverageLiquidity(410): FLOAT
    class WtAverageLiquidity:
        tag: int = 410

    # ExchangeForPhysical(411): BOOLEAN
    class ExchangeForPhysical:
        tag: int = 411
        NO: str = 'N'
        YES: str = 'Y'

    # OutMainCntryUIndex(412): AMT
    class OutMainCntryUIndex:
        tag: int = 412

    # CrossPercent(413): FLOAT
    class CrossPercent:
        tag: int = 413

    # ProgRptReqs(414): INT
    class ProgRptReqs:
        tag: int = 414
        BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST: int = 1
        SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS_PERIOD_OPTIONALLY_SPECIFIED_IN_PROGRESSPERIOD: int = 2
        REAL_TIME_EXECUTION_REPORTS: int = 3

    # ProgPeriodInterval(415): INT
    class ProgPeriodInterval:
        tag: int = 415

    # IncTaxInd(416): INT
    class IncTaxInd:
        tag: int = 416
        NET: int = 1
        GROSS: int = 2

    # NumBidders(417): INT
    class NumBidders:
        tag: int = 417

    # TradeType(418): CHAR
    class TradeType:
        tag: int = 418
        AGENCY: str = 'A'
        VWAP_GUARANTEE: str = 'G'
        GUARANTEED_CLOSE: str = 'J'
        RISK_TRADE: str = 'R'

    # BasisPxType(419): CHAR
    class BasisPxType:
        tag: int = 419
        CLOSING_PRICE_AT_MORNING_SESSION: str = '2'
        CLOSING_PRICE: str = '3'
        CURRENT_PRICE: str = '4'
        SQ: str = '5'
        VWAP_THROUGH_A_DAY: str = '6'
        VWAP_THROUGH_A_MORNING_SESSION: str = '7'
        VWAP_THROUGH_AN_AFTERNOON_SESSION: str = '8'
        VWAP_THROUGH_A_DAY_EXCEPT_YORI: str = '9'
        VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI: str = 'A'
        VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI: str = 'B'
        STRIKE: str = 'C'
        OPEN: str = 'D'
        OTHERS: str = 'Z'

    # NoBidComponents(420): INT
    class NoBidComponents:
        tag: int = 420

    # Country(421): STRING
    class Country:
        tag: int = 421

    # TotNoStrikes(422): INT
    class TotNoStrikes:
        tag: int = 422

    # PriceType(423): INT
    class PriceType:
        tag: int = 423
        PERCENTAGE: int = 1
        PER_SHARE: int = 2
        FIXED_AMOUNT: int = 3

    # DayOrderQty(424): QTY
    class DayOrderQty:
        tag: int = 424

    # DayCumQty(425): QTY
    class DayCumQty:
        tag: int = 425

    # DayAvgPx(426): PRICE
    class DayAvgPx:
        tag: int = 426

    # GTBookingInst(427): INT
    class GTBookingInst:
        tag: int = 427
        BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION: int = 0
        ACCUMULATE_EXECUTIONS_UNTIL_ORDER_IS_FILLED_OR_EXPIRES: int = 1
        ACCUMULATE_UNTIL_VERBALLY_NOTIFIED_OTHERWISE: int = 2

    # NoStrikes(428): INT
    class NoStrikes:
        tag: int = 428

    # ListStatusType(429): INT
    class ListStatusType:
        tag: int = 429

    # NetGrossInd(430): INT
    class NetGrossInd:
        tag: int = 430
        NET: int = 1
        GROSS: int = 2

    # ListOrderStatus(431): INT
    class ListOrderStatus:
        tag: int = 431

    # ExpireDate(432): LOCALMKTDATE
    class ExpireDate:
        tag: int = 432

    # ListExecInstType(433): CHAR
    class ListExecInstType:
        tag: int = 433
        IMMEDIATE: str = '1'
        WAIT_FOR_EXECUTE_INSTRUCTION: str = '2'

    # CxlRejResponseTo(434): CHAR
    class CxlRejResponseTo:
        tag: int = 434
        ORDER_CANCEL_REQUEST: str = '1'
        ORDER_CANCEL_REPLACE_REQUEST: str = '2'

    # UnderlyingCouponRate(435): FLOAT
    class UnderlyingCouponRate:
        tag: int = 435

    # UnderlyingContractMultiplier(436): FLOAT
    class UnderlyingContractMultiplier:
        tag: int = 436

    # ContraTradeQty(437): QTY
    class ContraTradeQty:
        tag: int = 437

    # ContraTradeTime(438): UTCTIMESTAMP
    class ContraTradeTime:
        tag: int = 438

    # ClearingFirm(439): STRING
    class ClearingFirm:
        tag: int = 439

    # ClearingAccount(440): STRING
    class ClearingAccount:
        tag: int = 440

    # LiquidityNumSecurities(441): INT
    class LiquidityNumSecurities:
        tag: int = 441

    # MultiLegReportingType(442): CHAR
    class MultiLegReportingType:
        tag: int = 442
        SINGLE_SECURITY: str = '1'
        INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY: str = '2'
        MULTI_LEG_SECURITY: str = '3'

    # StrikeTime(443): UTCTIMESTAMP
    class StrikeTime:
        tag: int = 443

    # ListStatusText(444): STRING
    class ListStatusText:
        tag: int = 444

    # EncodedListStatusTextLen(445): LENGTH
    class EncodedListStatusTextLen:
        tag: int = 445

    # EncodedListStatusText(446): DATA
    class EncodedListStatusText:
        tag: int = 446
