# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ufeapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ufeapi.proto',
  package='UFE',
  syntax='proto3',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x0cufeapi.proto\x12\x03UFE\"\xb4\x03\n\x08UFEField\x12\x30\n\x08location\x18\x01 \x01(\x0e\x32\x1e.UFE.UFEField.UFEFieldLocation\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.UFE.UFEField.UFEFieldType\x12\x0b\n\x03tag\x18\x03 \x01(\r\x12\x0c\n\x04ival\x18\x04 \x01(\x03\x12\x0c\n\x04\x66val\x18\x05 \x01(\x01\x12\x0c\n\x04\x62val\x18\x06 \x01(\x08\x12\x0c\n\x04sval\x18\x07 \x01(\x0c\x12\x1e\n\x04mval\x18\x08 \x03(\x0b\x32\x10.UFE.WireMessage\"M\n\x10UFEFieldLocation\x12\x0b\n\x07\x66l_body\x10\x00\x12\r\n\tfl_header\x10\x01\x12\x0e\n\nfl_trailer\x10\x02\x12\r\n\tfl_system\x10\x03\"\x97\x01\n\x0cUFEFieldType\x12\x0e\n\nft_unknown\x10\x00\x12\n\n\x06\x66t_int\x10\x01\x12\x0b\n\x07\x66t_char\x10\x02\x12\r\n\tft_double\x10\x03\x12\r\n\tft_string\x10\x04\x12\x0b\n\x07\x66t_bool\x10\x05\x12\x0b\n\x07\x66t_time\x10\x06\x12\n\n\x06\x66t_msg\x10\x07\x12\x0b\n\x07\x66t_uuid\x10\x08\x12\r\n\tft_status\x10\t\"\xce\x02\n\x0bWireMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08longname\x18\x02 \x01(\t\x12\x0b\n\x03seq\x18\x03 \x01(\r\x12#\n\x04type\x18\x04 \x01(\x0e\x32\x15.UFE.WireMessage.Type\x12\x12\n\nservice_id\x18\x05 \x01(\x05\x12\x15\n\rsubservice_id\x18\x06 \x01(\x05\x12\x1d\n\x06\x66ields\x18\x07 \x03(\x0b\x32\r.UFE.UFEField\"\xa2\x01\n\x04Type\x12\r\n\tst_fixmsg\x10\x00\x12\r\n\tst_system\x10\x01\x12\x12\n\x0est_servicelist\x10\x02\x12\x11\n\rst_dictionary\x10\x03\x12\x11\n\rst_sysstrings\x10\x04\x12\x0f\n\x0bst_response\x10\x05\x12\x0c\n\x08st_error\x10\x06\x12\x11\n\rst_servicelog\x10\x07\x12\x10\n\x0cst_heartbeat\x10\x08\x42\x02H\x03\x62\x06proto3')
)



_UFEFIELD_UFEFIELDLOCATION = _descriptor.EnumDescriptor(
  name='UFEFieldLocation',
  full_name='UFE.UFEField.UFEFieldLocation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='fl_body', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fl_header', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fl_trailer', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fl_system', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=227,
  serialized_end=304,
)
_sym_db.RegisterEnumDescriptor(_UFEFIELD_UFEFIELDLOCATION)

_UFEFIELD_UFEFIELDTYPE = _descriptor.EnumDescriptor(
  name='UFEFieldType',
  full_name='UFE.UFEField.UFEFieldType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ft_unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_int', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_char', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_double', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_string', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_bool', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_time', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_msg', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_uuid', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ft_status', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=307,
  serialized_end=458,
)
_sym_db.RegisterEnumDescriptor(_UFEFIELD_UFEFIELDTYPE)

_WIREMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='UFE.WireMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='st_fixmsg', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='st_system', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='st_servicelist', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='st_dictionary', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='st_sysstrings', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='st_response', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='st_error', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='st_servicelog', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='st_heartbeat', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=633,
  serialized_end=795,
)
_sym_db.RegisterEnumDescriptor(_WIREMESSAGE_TYPE)


_UFEFIELD = _descriptor.Descriptor(
  name='UFEField',
  full_name='UFE.UFEField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='UFE.UFEField.location', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='UFE.UFEField.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='UFE.UFEField.tag', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ival', full_name='UFE.UFEField.ival', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fval', full_name='UFE.UFEField.fval', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bval', full_name='UFE.UFEField.bval', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sval', full_name='UFE.UFEField.sval', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mval', full_name='UFE.UFEField.mval', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UFEFIELD_UFEFIELDLOCATION,
    _UFEFIELD_UFEFIELDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=458,
)


_WIREMESSAGE = _descriptor.Descriptor(
  name='WireMessage',
  full_name='UFE.WireMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UFE.WireMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longname', full_name='UFE.WireMessage.longname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='UFE.WireMessage.seq', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='UFE.WireMessage.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_id', full_name='UFE.WireMessage.service_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subservice_id', full_name='UFE.WireMessage.subservice_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='UFE.WireMessage.fields', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WIREMESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=795,
)

_UFEFIELD.fields_by_name['location'].enum_type = _UFEFIELD_UFEFIELDLOCATION
_UFEFIELD.fields_by_name['type'].enum_type = _UFEFIELD_UFEFIELDTYPE
_UFEFIELD.fields_by_name['mval'].message_type = _WIREMESSAGE
_UFEFIELD_UFEFIELDLOCATION.containing_type = _UFEFIELD
_UFEFIELD_UFEFIELDTYPE.containing_type = _UFEFIELD
_WIREMESSAGE.fields_by_name['type'].enum_type = _WIREMESSAGE_TYPE
_WIREMESSAGE.fields_by_name['fields'].message_type = _UFEFIELD
_WIREMESSAGE_TYPE.containing_type = _WIREMESSAGE
DESCRIPTOR.message_types_by_name['UFEField'] = _UFEFIELD
DESCRIPTOR.message_types_by_name['WireMessage'] = _WIREMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UFEField = _reflection.GeneratedProtocolMessageType('UFEField', (_message.Message,), {
  'DESCRIPTOR' : _UFEFIELD,
  '__module__' : 'ufeapi_pb2'
  # @@protoc_insertion_point(class_scope:UFE.UFEField)
  })
_sym_db.RegisterMessage(UFEField)

WireMessage = _reflection.GeneratedProtocolMessageType('WireMessage', (_message.Message,), {
  'DESCRIPTOR' : _WIREMESSAGE,
  '__module__' : 'ufeapi_pb2'
  # @@protoc_insertion_point(class_scope:UFE.WireMessage)
  })
_sym_db.RegisterMessage(WireMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
